In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly
import os

In [2]:
os.getcwd()

'C:\\Users\\nitish\\Desktop\\MSc_Komal\\R\\Project\\Life Expectancy'

In [3]:
# reading two csv files
data1 = pd.read_csv('life-expectancy-vs-gdp-per-capita.csv')
data2 = pd.read_csv('poverty-vs-life-expectancy.csv')

# using merge function by setting how='inner'
output1 = pd.merge(data1, data2,on=['Entity','Year'],how='outer')

# displaying result
np.shape(output1)
#output1.drop(['Code_x','Population (historical estimates)_x','Continent_x'],inplace=True,axis=1)
output1.fillna(0)

,Entity,Code_x,Year,Life expectancy,GDP per capita,145446-annotations,Population (historical estimates)_x,Continent_x,Code_y,"Life expectancy at birth, total (years)",$3.20 per day - share of population below poverty line,Population (historical estimates)_y,Continent_y
0,Abkhazia,OWID_ABK,2015,0.000,0.0,0,0.0,Asia,OWID_ABK,0.000000,0.0,0.0,Asia
1,Afghanistan,AFG,1950,27.638,1156.0,0,7752117.0,0,AFG,0.000000,0.0,7752117.0,0
2,Afghanistan,AFG,1951,27.878,1170.0,0,7840151.0,0,AFG,0.000000,0.0,7840151.0,0
3,Afghanistan,AFG,1952,28.361,1189.0,0,7935996.0,0,AFG,0.000000,0.0,7935996.0,0
4,Afghanistan,AFG,1953,28.852,1240.0,0,8039684.0,0,AFG,0.000000,0.0,8039684.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63309,Upper middle income,0,2015,0.000,0.0,0,0.0,0,0,74.994105,0.0,0.0,0
63310,Upper middle income,0,2016,0.000,0.0,0,0.0,0,0,75.262635,0.0,0.0,0
63311,Upper middle income,0,2017,0.000,0.0,0,0.0,0,0,75.529973,0.0,0.0,0
63312,Upper middle income,0,2018,0.000,0.0,0,0.0,0,0,75.741121,0.0,0.0,0
63313,Upper middle income,0,2019,0.000,0.0,0,0.0,0,0,75.943064,0.0,0.0,0

In [4]:

Life_Exp=output1.drop(['Code_y','Population (historical estimates)_y','Life expectancy at birth, total (years)','145446-annotations','Continent_x','Continent_y'], axis = 1)
# Life_Exp=Country_data1.drop(['Continent_x'], axis = 1)

In [5]:
Life_Exp.nunique()

Entity                                                      364
Code_x                                                      286
Year                                                        797
Life expectancy                                           15300
GDP per capita                                            11343
Population (historical estimates)_x                       51142
$3.20 per day - share of population below poverty line     6405
dtype: int64

In [6]:
Life_Exp.Year.unique()

array([  2015,   1950,   1951,   1952,   1953,   1954,   1955,   1956,
         1957,   1958,   1959,   1960,   1961,   1962,   1963,   1964,
         1965,   1966,   1967,   1968,   1969,   1970,   1971,   1972,
         1973,   1974,   1975,   1976,   1977,   1978,   1979,   1980,
         1981,   1982,   1983,   1984,   1985,   1986,   1987,   1988,
         1989,   1990,   1991,   1992,   1993,   1994,   1995,   1996,
         1997,   1998,   1999,   2000,   2001,   2002,   2003,   2004,
         2005,   2006,   2007,   2008,   2009,   2010,   2011,   2012,
         2013,   2014,   2016,   2017,   2018,   2019, -10000,  -9000,
        -8000,  -7000,  -6000,  -5000,  -4000,  -3000,  -2000,  -1000,
            0,    100,    200,    300,    400,    500,    600,    700,
          800,    900,   1000,   1100,   1200,   1300,   1400,   1500,
         1600,   1700,   1710,   1720,   1730,   1740,   1750,   1760,
         1770,   1780,   1790,   1800,   1801,   1802,   1803,   1804,
         1805,   1806,   1807,   1808,   1809,   1810,   1811,   1812,
         1813,   1814,   1815,   1816,   1817,   1818,   1819,   1820,
         1821,   1822,   1823,   1824,   1825,   1826,   1827,   1828,
         1829,   1830,   1831,   1832,   1833,   1834,   1835,   1836,
         1837,   1838,   1839,   1840,   1841,   1842,   1843,   1844,
         1845,   1846,   1847,   1848,   1849,   1850,   1851,   1852,
         1853,   1854,   1855,   1856,   1857,   1858,   1859,   1860,
         1861,   1862,   1863,   1864,   1865,   1866,   1867,   1868,
         1869,   1870,   1871,   1872,   1873,   1874,   1875,   1876,
         1877,   1878,   1879,   1880,   1881,   1882,   1883,   1884,
         1885,   1886,   1887,   1888,   1889,   1890,   1891,   1892,
         1893,   1894,   1895,   1896,   1897,   1898,   1899,   1900,
         1901,   1902,   1903,   1904,   1905,   1906,   1907,   1908,
         1909,   1910,   1911,   1912,   1913,   1914,   1915,   1916,
         1917,   1918,   1919,   1920,   1921,   1922,   1923,   1924,
         1925,   1926,   1927,   1928,   1929,   1930,   1931,   1932,
         1933,   1934,   1935,   1936,   1937,   1938,   1939,   1940,
         1941,   1942,   1943,   1944,   1945,   1946,   1947,   1948,
         1949,   2020,   2021,      1,   1550,   1650,   1090,   1120,
         1410,   1420,   1430,   1440,   1450,   1460,   1470,   1480,
         1490,   1510,   1520,   1530,   1540,   1560,   1570,   1580,
         1590,   1610,   1620,   1661,   1685,   1690,   1724,   1766,
         1775,   1792,    730,   1280,   1755,   1765,   1785,   1795,
         1281,   1282,   1283,   1284,   1285,   1286,   1287,   1288,
         1289,   1290,   1291,   1292,   1293,   1294,   1295,   1296,
         1297,   1298,   1299,   1301,   1302,   1303,   1304,   1305,
         1306,   1307,   1308,   1309,   1310,   1311,   1312,   1313,
         1314,   1315,   1316,   1317,   1318,   1319,   1320,   1321,
         1322,   1323,   1324,   1325,   1326,   1327,   1328,   1329,
         1330,   1331,   1332,   1333,   1334,   1335,   1336,   1337,
         1338,   1339,   1340,   1341,   1342,   1343,   1344,   1345,
         1346,   1347,   1348,   1349,   1350,   1351,   1352,   1353,
         1354,   1355,   1356,   1357,   1358,   1359,   1360,   1361,
         1362,   1363,   1364,   1365,   1366,   1367,   1368,   1369,
         1370,   1371,   1372,   1373,   1374,   1375,   1376,   1377,
         1378,   1379,   1380,   1381,   1382,   1383,   1384,   1385,
         1386,   1387,   1388,   1389,   1390,   1391,   1392,   1393,
         1394,   1395,   1396,   1397,   1398,   1399,   1401,   1402,
         1403,   1404,   1405,   1406,   1407,   1408,   1409,   1411,
         1412,   1413,   1414,   1415,   1416,   1417,   1418,   1419,
         1421,   1422,   1423,   1424,   1425,   1426,   1427,   1428,
         1429,   1431,   1432,   1433,   1434,   1435,   1436,   1437,
         1438,   1439,   1441,   1442,   1443,   1444,   1445,   1446,
         1447,   1448,   1449,   1451,   1452,   1453,   1454,   1455,
         1456,   1457,   1458,   1459,   1461,   1462,   1463,   1464,
         1465,   1466,   1467,   1468,   1469,   1471,   1472,   1473,
         1474,   1475,   1476,   1477,   1478,   1479,   1481,   1482,
         1483,   1484,   1485,   1486,   1487,   1488,   1489,   1491,
         1492,   1493,   1494,   1495,   1496,   1497,   1498,   1499,
         1501,   1502,   1503,   1504,   1505,   1506,   1507,   1508,
         1509,   1511,   1512,   1513,   1514,   1515,   1516,   1517,
         1518,   1519,   1521,   1522,   1523,   1524,   1525,   1526,
         1527,   1528,   1529,   1531,   1532,   1533,   1534,   1535,
         1536,   1537,   1538,   1539,   1541,   1542,   1543,   1544,
         1545,   1546,   1547,   1548,   1549,   1551,   1552,   1553,
         1554,   1555,   1556,   1557,   1558,   1559,   1561,   1562,
         1563,   1564,   1565,   1566,   1567,   1568,   1569,   1571,
         1572,   1573,   1574,   1575,   1576,   1577,   1578,   1579,
         1581,   1582,   1583,   1584,   1585,   1586,   1587,   1588,
         1589,   1591,   1592,   1593,   1594,   1595,   1596,   1597,
         1598,   1599,   1601,   1602,   1603,   1604,   1605,   1606,
         1607,   1608,   1609,   1611,   1612,   1613,   1614,   1615,
         1616,   1617,   1618,   1619,   1621,   1622,   1623,   1624,
         1625,   1626,   1627,   1628,   1629,   1630,   1631,   1632,
         1633,   1634,   1635,   1636,   1637,   1638,   1639,   1640,
         1641,   1642,   1643,   1644,   1645,   1646,   1647,   1648,
         1649,   1651,   1652,   1653,   1654,   1655,   1656,   1657,
         1658,   1659,   1660,   1662,   1663,   1664,   1665,   1666,
         1667,   1668,   1669,   1670,   1671,   1672,   1673,   1674,
         1675,   1676,   1677,   1678,   1679,   1680,   1681,   1682,
         1683,   1684,   1686,   1687,   1688,   1689,   1691,   1692,
         1693,   1694,   1695,   1696,   1697,   1698,   1699,   1701,
         1702,   1703,   1704,   1705,   1706,   1707,   1708,   1709,
         1711,   1712,   1713,   1714,   1715,   1716,   1717,   1718,
         1719,   1721,   1722,   1723,   1725,   1726,   1727,   1728,
         1729,   1731,   1732,   1733,   1734,   1735,   1736,   1737,
         1738,   1739,   1741,   1742,   1743,   1744,   1745,   1746,
         1747,   1748,   1749,   1751,   1752,   1753,   1754,   1756,
         1757,   1758,   1759,   1761,   1762,   1763,   1764,   1767,
         1768,   1769,   1771,   1772,   1773,   1774,   1776,   1777,
         1778,   1779,   1781,   1782,   1783,   1784,   1786,   1787,
         1788,   1789,   1791,   1793,   1794,   1796,   1797,   1798,
         1799,   1252,   1253,   1254,   1255,   1256,   1257,   1258,
         1259,   1260,   1261,   1262,   1263,   1264,   1265,   1266,
         1267,   1268,   1269,   1270,   1271,   1272,   1273,   1274,
         1275,   1276,   1277,   1278,   1279], dtype=int64)

In [7]:
Life_Exp.duplicated().sum()

0

In [8]:
data3 = pd.read_csv('extreme-poverty-headcount-ratio-vs-life-expectancy-at-birth.csv')
Life_Exp = pd.merge(data3, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

# displaying result
np.shape(Life_Exp)
Life_Exp=Life_Exp.fillna(0)
Life_Exp.head()

,Entity,Code,Year,$1.90 per day - share of population below poverty line,"Life expectancy at birth, total (years)",Population (historical estimates),Continent,Code_x,Life expectancy,GDP per capita,Population (historical estimates)_x,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015,0.0,0.000,0.0,Asia,OWID_ABK,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,1960,0.0,32.446,8996967.0,0,AFG,32.446,1326.0,8996967.0,0.0
2,Afghanistan,AFG,1961,0.0,32.962,9169406.0,0,AFG,32.962,1309.0,9169406.0,0.0
3,Afghanistan,AFG,1962,0.0,33.471,9351442.0,0,AFG,33.471,1302.0,9351442.0,0.0
4,Afghanistan,AFG,1963,0.0,33.971,9543200.0,0,AFG,33.971,1298.0,9543200.0,0.0

In [9]:
Life_Exp.drop(['Code_x','Population (historical estimates)_x','Life expectancy at birth, total (years)','Continent'],inplace=True,axis=1)

In [10]:
Life_Exp.head()

,Entity,Code,Year,$1.90 per day - share of population below poverty line,Population (historical estimates),Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015,0.0,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1960,0.0,8996967.0,32.446,1326.0,0.0
2,Afghanistan,AFG,1961,0.0,9169406.0,32.962,1309.0,0.0
3,Afghanistan,AFG,1962,0.0,9351442.0,33.471,1302.0,0.0
4,Afghanistan,AFG,1963,0.0,9543200.0,33.971,1298.0,0.0

In [11]:
Life_Exp.fillna(0)

,Entity,Code,Year,$1.90 per day - share of population below poverty line,Population (historical estimates),Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015,0.0,0.0,0.000,0.000000,0.0
1,Afghanistan,AFG,1960,0.0,8996967.0,32.446,1326.000000,0.0
2,Afghanistan,AFG,1961,0.0,9169406.0,32.962,1309.000000,0.0
3,Afghanistan,AFG,1962,0.0,9351442.0,33.471,1302.000000,0.0
4,Afghanistan,AFG,1963,0.0,9543200.0,33.971,1298.000000,0.0
...,...,...,...,...,...,...,...,...
63309,Western Offshoots,0,2000,0.0,0.0,0.000,44329.268173,0.0
63310,Western Offshoots,0,2010,0.0,0.0,0.000,48090.150588,0.0
63311,Western Offshoots,0,2016,0.0,0.0,0.000,51667.975829,0.0
63312,Western Offshoots,0,2017,0.0,0.0,0.000,52597.218348,0.0
63313,Western Offshoots,0,2018,0.0,0.0,0.000,53756.496545,0.0

In [12]:
Life_Exp.Year.unique()

array([  2015,   1960,   1961,   1962,   1963,   1964,   1965,   1966,
         1967,   1968,   1969,   1970,   1971,   1972,   1973,   1974,
         1975,   1976,   1977,   1978,   1979,   1980,   1981,   1982,
         1983,   1984,   1985,   1986,   1987,   1988,   1989,   1990,
         1991,   1992,   1993,   1994,   1995,   1996,   1997,   1998,
         1999,   2000,   2001,   2002,   2003,   2004,   2005,   2006,
         2007,   2008,   2009,   2010,   2011,   2012,   2013,   2014,
         2016,   2017,   2018,   2019, -10000,  -9000,  -8000,  -7000,
        -6000,  -5000,  -4000,  -3000,  -2000,  -1000,      0,    100,
          200,    300,    400,    500,    600,    700,    800,    900,
         1000,   1100,   1200,   1300,   1400,   1500,   1600,   1700,
         1710,   1720,   1730,   1740,   1750,   1760,   1770,   1780,
         1790,   1800,   1801,   1802,   1803,   1804,   1805,   1806,
         1807,   1808,   1809,   1810,   1811,   1812,   1813,   1814,
         1815,   1816,   1817,   1818,   1819,   1820,   1821,   1822,
         1823,   1824,   1825,   1826,   1827,   1828,   1829,   1830,
         1831,   1832,   1833,   1834,   1835,   1836,   1837,   1838,
         1839,   1840,   1841,   1842,   1843,   1844,   1845,   1846,
         1847,   1848,   1849,   1850,   1851,   1852,   1853,   1854,
         1855,   1856,   1857,   1858,   1859,   1860,   1861,   1862,
         1863,   1864,   1865,   1866,   1867,   1868,   1869,   1870,
         1871,   1872,   1873,   1874,   1875,   1876,   1877,   1878,
         1879,   1880,   1881,   1882,   1883,   1884,   1885,   1886,
         1887,   1888,   1889,   1890,   1891,   1892,   1893,   1894,
         1895,   1896,   1897,   1898,   1899,   1900,   1901,   1902,
         1903,   1904,   1905,   1906,   1907,   1908,   1909,   1910,
         1911,   1912,   1913,   1914,   1915,   1916,   1917,   1918,
         1919,   1920,   1921,   1922,   1923,   1924,   1925,   1926,
         1927,   1928,   1929,   1930,   1931,   1932,   1933,   1934,
         1935,   1936,   1937,   1938,   1939,   1940,   1941,   1942,
         1943,   1944,   1945,   1946,   1947,   1948,   1949,   1950,
         1951,   1952,   1953,   1954,   1955,   1956,   1957,   1958,
         1959,   2020,   2021,      1,   1550,   1650,   1090,   1120,
         1410,   1420,   1430,   1440,   1450,   1460,   1470,   1480,
         1490,   1510,   1520,   1530,   1540,   1560,   1570,   1580,
         1590,   1610,   1620,   1661,   1685,   1690,   1724,   1766,
         1775,   1792,    730,   1280,   1755,   1765,   1785,   1795,
         1281,   1282,   1283,   1284,   1285,   1286,   1287,   1288,
         1289,   1290,   1291,   1292,   1293,   1294,   1295,   1296,
         1297,   1298,   1299,   1301,   1302,   1303,   1304,   1305,
         1306,   1307,   1308,   1309,   1310,   1311,   1312,   1313,
         1314,   1315,   1316,   1317,   1318,   1319,   1320,   1321,
         1322,   1323,   1324,   1325,   1326,   1327,   1328,   1329,
         1330,   1331,   1332,   1333,   1334,   1335,   1336,   1337,
         1338,   1339,   1340,   1341,   1342,   1343,   1344,   1345,
         1346,   1347,   1348,   1349,   1350,   1351,   1352,   1353,
         1354,   1355,   1356,   1357,   1358,   1359,   1360,   1361,
         1362,   1363,   1364,   1365,   1366,   1367,   1368,   1369,
         1370,   1371,   1372,   1373,   1374,   1375,   1376,   1377,
         1378,   1379,   1380,   1381,   1382,   1383,   1384,   1385,
         1386,   1387,   1388,   1389,   1390,   1391,   1392,   1393,
         1394,   1395,   1396,   1397,   1398,   1399,   1401,   1402,
         1403,   1404,   1405,   1406,   1407,   1408,   1409,   1411,
         1412,   1413,   1414,   1415,   1416,   1417,   1418,   1419,
         1421,   1422,   1423,   1424,   1425,   1426,   1427,   1428,
         1429,   1431,   1432,   1433,   1434,   1435,   1436,   1437,
         1438,   1439,   1441,   1442,   1443,   1444,   1445,   1446,
         1447,   1448,   1449,   1451,   1452,   1453,   1454,   1455,
         1456,   1457,   1458,   1459,   1461,   1462,   1463,   1464,
         1465,   1466,   1467,   1468,   1469,   1471,   1472,   1473,
         1474,   1475,   1476,   1477,   1478,   1479,   1481,   1482,
         1483,   1484,   1485,   1486,   1487,   1488,   1489,   1491,
         1492,   1493,   1494,   1495,   1496,   1497,   1498,   1499,
         1501,   1502,   1503,   1504,   1505,   1506,   1507,   1508,
         1509,   1511,   1512,   1513,   1514,   1515,   1516,   1517,
         1518,   1519,   1521,   1522,   1523,   1524,   1525,   1526,
         1527,   1528,   1529,   1531,   1532,   1533,   1534,   1535,
         1536,   1537,   1538,   1539,   1541,   1542,   1543,   1544,
         1545,   1546,   1547,   1548,   1549,   1551,   1552,   1553,
         1554,   1555,   1556,   1557,   1558,   1559,   1561,   1562,
         1563,   1564,   1565,   1566,   1567,   1568,   1569,   1571,
         1572,   1573,   1574,   1575,   1576,   1577,   1578,   1579,
         1581,   1582,   1583,   1584,   1585,   1586,   1587,   1588,
         1589,   1591,   1592,   1593,   1594,   1595,   1596,   1597,
         1598,   1599,   1601,   1602,   1603,   1604,   1605,   1606,
         1607,   1608,   1609,   1611,   1612,   1613,   1614,   1615,
         1616,   1617,   1618,   1619,   1621,   1622,   1623,   1624,
         1625,   1626,   1627,   1628,   1629,   1630,   1631,   1632,
         1633,   1634,   1635,   1636,   1637,   1638,   1639,   1640,
         1641,   1642,   1643,   1644,   1645,   1646,   1647,   1648,
         1649,   1651,   1652,   1653,   1654,   1655,   1656,   1657,
         1658,   1659,   1660,   1662,   1663,   1664,   1665,   1666,
         1667,   1668,   1669,   1670,   1671,   1672,   1673,   1674,
         1675,   1676,   1677,   1678,   1679,   1680,   1681,   1682,
         1683,   1684,   1686,   1687,   1688,   1689,   1691,   1692,
         1693,   1694,   1695,   1696,   1697,   1698,   1699,   1701,
         1702,   1703,   1704,   1705,   1706,   1707,   1708,   1709,
         1711,   1712,   1713,   1714,   1715,   1716,   1717,   1718,
         1719,   1721,   1722,   1723,   1725,   1726,   1727,   1728,
         1729,   1731,   1732,   1733,   1734,   1735,   1736,   1737,
         1738,   1739,   1741,   1742,   1743,   1744,   1745,   1746,
         1747,   1748,   1749,   1751,   1752,   1753,   1754,   1756,
         1757,   1758,   1759,   1761,   1762,   1763,   1764,   1767,
         1768,   1769,   1771,   1772,   1773,   1774,   1776,   1777,
         1778,   1779,   1781,   1782,   1783,   1784,   1786,   1787,
         1788,   1789,   1791,   1793,   1794,   1796,   1797,   1798,
         1799,   1252,   1253,   1254,   1255,   1256,   1257,   1258,
         1259,   1260,   1261,   1262,   1263,   1264,   1265,   1266,
         1267,   1268,   1269,   1270,   1271,   1272,   1273,   1274,
         1275,   1276,   1277,   1278,   1279], dtype=int64)

In [13]:
data4 = pd.read_csv('life-satisfaction-vs-life-expectancy.csv')
Life_Exp = pd.merge(data4, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

(65875, 14)

In [14]:
Life_Exp.duplicated().sum()

0

In [15]:
Life_Exp.head()

,Entity,Code_x,Year,"Estimates, 1950 - 2020: Annually interpolated demographic indicators - Life expectancy at birth, both sexes combined (years)",Life satisfaction in Cantril Ladder (World Happiness Report 2021),Year.1,Population (historical estimates)_x,Continent,Code_y,$1.90 per day - share of population below poverty line,Population (historical estimates)_y,Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015.0,NaN,NaN,NaN,NaN,Asia,OWID_ABK,0.0,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1950.0,27.638,3.983,2015.0,7752117.0,NaN,AFG,0.0,7752117.0,27.638,1156.0,0.0
2,Afghanistan,AFG,1951.0,27.878,3.983,2015.0,7840151.0,NaN,AFG,0.0,7840151.0,27.878,1170.0,0.0
3,Afghanistan,AFG,1952.0,28.361,3.983,2015.0,7935996.0,NaN,AFG,0.0,7935996.0,28.361,1189.0,0.0
4,Afghanistan,AFG,1953.0,28.852,3.983,2015.0,8039684.0,NaN,AFG,0.0,8039684.0,28.852,1240.0,0.0

In [16]:
Life_Exp.drop(['Estimates, 1950 - 2020: Annually interpolated demographic indicators - Life expectancy at birth, both sexes combined (years)','Code_y','Continent','Population (historical estimates)_y','Year.1'],inplace=True,axis=1)

In [17]:
Life_Exp.head()

,Entity,Code_x,Year,Life satisfaction in Cantril Ladder (World Happiness Report 2021),Population (historical estimates)_x,$1.90 per day - share of population below poverty line,Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015.0,NaN,NaN,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1950.0,3.983,7752117.0,0.0,27.638,1156.0,0.0
2,Afghanistan,AFG,1951.0,3.983,7840151.0,0.0,27.878,1170.0,0.0
3,Afghanistan,AFG,1952.0,3.983,7935996.0,0.0,28.361,1189.0,0.0
4,Afghanistan,AFG,1953.0,3.983,8039684.0,0.0,28.852,1240.0,0.0

In [18]:
Life_Exp=Life_Exp.fillna(0)
Life_Exp.head()

,Entity,Code_x,Year,Life satisfaction in Cantril Ladder (World Happiness Report 2021),Population (historical estimates)_x,$1.90 per day - share of population below poverty line,Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015.0,0.000,0.0,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1950.0,3.983,7752117.0,0.0,27.638,1156.0,0.0
2,Afghanistan,AFG,1951.0,3.983,7840151.0,0.0,27.878,1170.0,0.0
3,Afghanistan,AFG,1952.0,3.983,7935996.0,0.0,28.361,1189.0,0.0
4,Afghanistan,AFG,1953.0,3.983,8039684.0,0.0,28.852,1240.0,0.0

In [19]:
data5 = pd.read_csv('life-expectancy-vs-healthcare-expenditure.csv')
Life_Exp = pd.merge(data5, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

(65989, 14)

In [20]:
Life_Exp.head()

,Entity,Code,Year,"Life expectancy at birth, total (years)","Health expenditure per capita, PPP (constant 2011 international $)",Population (historical estimates),Continent,Code_x,Life satisfaction in Cantril Ladder (World Happiness Report 2021),Population (historical estimates)_x,$1.90 per day - share of population below poverty line,Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015.0,NaN,NaN,NaN,Asia,OWID_ABK,0.000,0.0,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1960.0,32.292,NaN,8996967.0,NaN,AFG,3.983,8996967.0,0.0,32.446,1326.0,0.0
2,Afghanistan,AFG,1961.0,32.742,NaN,9169406.0,NaN,AFG,3.983,9169406.0,0.0,32.962,1309.0,0.0
3,Afghanistan,AFG,1962.0,33.185,NaN,9351442.0,NaN,AFG,3.983,9351442.0,0.0,33.471,1302.0,0.0
4,Afghanistan,AFG,1963.0,33.624,NaN,9543200.0,NaN,AFG,3.983,9543200.0,0.0,33.971,1298.0,0.0

In [21]:
Life_Exp.Year.unique()

array([ 2.015e+03,  1.960e+03,  1.961e+03,  1.962e+03,  1.963e+03,
        1.964e+03,  1.965e+03,  1.966e+03,  1.967e+03,  1.968e+03,
        1.969e+03,  1.970e+03,  1.971e+03,  1.972e+03,  1.973e+03,
        1.974e+03,  1.975e+03,  1.976e+03,  1.977e+03,  1.978e+03,
        1.979e+03,  1.980e+03,  1.981e+03,  1.982e+03,  1.983e+03,
        1.984e+03,  1.985e+03,  1.986e+03,  1.987e+03,  1.988e+03,
        1.989e+03,  1.990e+03,  1.991e+03,  1.992e+03,  1.993e+03,
        1.994e+03,  1.995e+03,  1.996e+03,  1.997e+03,  1.998e+03,
        1.999e+03,  2.000e+03,  2.001e+03,  2.002e+03,  2.003e+03,
        2.004e+03,  2.005e+03,  2.006e+03,  2.007e+03,  2.008e+03,
        2.009e+03,  2.010e+03,  2.011e+03,  2.012e+03,  2.013e+03,
        2.014e+03,  2.016e+03, -1.000e+04, -9.000e+03, -8.000e+03,
       -7.000e+03, -6.000e+03, -5.000e+03, -4.000e+03, -3.000e+03,
       -2.000e+03, -1.000e+03,  0.000e+00,  1.000e+02,  2.000e+02,
        3.000e+02,  4.000e+02,  5.000e+02,  6.000e+02,  7.000e+02,
        8.000e+02,  9.000e+02,  1.000e+03,  1.100e+03,  1.200e+03,
        1.300e+03,  1.400e+03,  1.500e+03,  1.600e+03,  1.700e+03,
        1.710e+03,  1.720e+03,  1.730e+03,  1.740e+03,  1.750e+03,
        1.760e+03,  1.770e+03,  1.780e+03,  1.790e+03,  1.800e+03,
        1.801e+03,  1.802e+03,  1.803e+03,  1.804e+03,  1.805e+03,
        1.806e+03,  1.807e+03,  1.808e+03,  1.809e+03,  1.810e+03,
        1.811e+03,  1.812e+03,  1.813e+03,  1.814e+03,  1.815e+03,
        1.816e+03,  1.817e+03,  1.818e+03,  1.819e+03,  1.820e+03,
        1.821e+03,  1.822e+03,  1.823e+03,  1.824e+03,  1.825e+03,
        1.826e+03,  1.827e+03,  1.828e+03,  1.829e+03,  1.830e+03,
        1.831e+03,  1.832e+03,  1.833e+03,  1.834e+03,  1.835e+03,
        1.836e+03,  1.837e+03,  1.838e+03,  1.839e+03,  1.840e+03,
        1.841e+03,  1.842e+03,  1.843e+03,  1.844e+03,  1.845e+03,
        1.846e+03,  1.847e+03,  1.848e+03,  1.849e+03,  1.850e+03,
        1.851e+03,  1.852e+03,  1.853e+03,  1.854e+03,  1.855e+03,
        1.856e+03,  1.857e+03,  1.858e+03,  1.859e+03,  1.860e+03,
        1.861e+03,  1.862e+03,  1.863e+03,  1.864e+03,  1.865e+03,
        1.866e+03,  1.867e+03,  1.868e+03,  1.869e+03,  1.870e+03,
        1.871e+03,  1.872e+03,  1.873e+03,  1.874e+03,  1.875e+03,
        1.876e+03,  1.877e+03,  1.878e+03,  1.879e+03,  1.880e+03,
        1.881e+03,  1.882e+03,  1.883e+03,  1.884e+03,  1.885e+03,
        1.886e+03,  1.887e+03,  1.888e+03,  1.889e+03,  1.890e+03,
        1.891e+03,  1.892e+03,  1.893e+03,  1.894e+03,  1.895e+03,
        1.896e+03,  1.897e+03,  1.898e+03,  1.899e+03,  1.900e+03,
        1.901e+03,  1.902e+03,  1.903e+03,  1.904e+03,  1.905e+03,
        1.906e+03,  1.907e+03,  1.908e+03,  1.909e+03,  1.910e+03,
        1.911e+03,  1.912e+03,  1.913e+03,  1.914e+03,  1.915e+03,
        1.916e+03,  1.917e+03,  1.918e+03,  1.919e+03,  1.920e+03,
        1.921e+03,  1.922e+03,  1.923e+03,  1.924e+03,  1.925e+03,
        1.926e+03,  1.927e+03,  1.928e+03,  1.929e+03,  1.930e+03,
        1.931e+03,  1.932e+03,  1.933e+03,  1.934e+03,  1.935e+03,
        1.936e+03,  1.937e+03,  1.938e+03,  1.939e+03,  1.940e+03,
        1.941e+03,  1.942e+03,  1.943e+03,  1.944e+03,  1.945e+03,
        1.946e+03,  1.947e+03,  1.948e+03,  1.949e+03,  1.950e+03,
        1.951e+03,  1.952e+03,  1.953e+03,  1.954e+03,  1.955e+03,
        1.956e+03,  1.957e+03,  1.958e+03,  1.959e+03,  2.017e+03,
        2.018e+03,  2.019e+03,  2.020e+03,  2.021e+03,  1.000e+00,
        1.550e+03,  1.650e+03,  1.090e+03,  1.120e+03,  1.410e+03,
        1.420e+03,  1.430e+03,  1.440e+03,  1.450e+03,  1.460e+03,
        1.470e+03,  1.480e+03,  1.490e+03,  1.510e+03,  1.520e+03,
        1.530e+03,  1.540e+03,  1.560e+03,  1.570e+03,  1.580e+03,
        1.590e+03,  1.610e+03,  1.620e+03,  1.661e+03,  1.685e+03,
        1.690e+03,  1.724e+03,  1.766e+03,  1.775e+03,  1.792e+03,
        7.300e+02,  1.280e+03,  1.755e+03,  1.765e+03,  1.785e+03,
        1.795e+03,  1.281e+03,  1.282e+03,  1.283e+03,  1.284e+03,
        1.285e+03,  1.286e+03,  1.287e+03,  1.288e+03,  1.289e+03,
        1.290e+03,  1.291e+03,  1.292e+03,  1.293e+03,  1.294e+03,
        1.295e+03,  1.296e+03,  1.297e+03,  1.298e+03,  1.299e+03,
        1.301e+03,  1.302e+03,  1.303e+03,  1.304e+03,  1.305e+03,
        1.306e+03,  1.307e+03,  1.308e+03,  1.309e+03,  1.310e+03,
        1.311e+03,  1.312e+03,  1.313e+03,  1.314e+03,  1.315e+03,
        1.316e+03,  1.317e+03,  1.318e+03,  1.319e+03,  1.320e+03,
        1.321e+03,  1.322e+03,  1.323e+03,  1.324e+03,  1.325e+03,
        1.326e+03,  1.327e+03,  1.328e+03,  1.329e+03,  1.330e+03,
        1.331e+03,  1.332e+03,  1.333e+03,  1.334e+03,  1.335e+03,
        1.336e+03,  1.337e+03,  1.338e+03,  1.339e+03,  1.340e+03,
        1.341e+03,  1.342e+03,  1.343e+03,  1.344e+03,  1.345e+03,
        1.346e+03,  1.347e+03,  1.348e+03,  1.349e+03,  1.350e+03,
        1.351e+03,  1.352e+03,  1.353e+03,  1.354e+03,  1.355e+03,
        1.356e+03,  1.357e+03,  1.358e+03,  1.359e+03,  1.360e+03,
        1.361e+03,  1.362e+03,  1.363e+03,  1.364e+03,  1.365e+03,
        1.366e+03,  1.367e+03,  1.368e+03,  1.369e+03,  1.370e+03,
        1.371e+03,  1.372e+03,  1.373e+03,  1.374e+03,  1.375e+03,
        1.376e+03,  1.377e+03,  1.378e+03,  1.379e+03,  1.380e+03,
        1.381e+03,  1.382e+03,  1.383e+03,  1.384e+03,  1.385e+03,
        1.386e+03,  1.387e+03,  1.388e+03,  1.389e+03,  1.390e+03,
        1.391e+03,  1.392e+03,  1.393e+03,  1.394e+03,  1.395e+03,
        1.396e+03,  1.397e+03,  1.398e+03,  1.399e+03,  1.401e+03,
        1.402e+03,  1.403e+03,  1.404e+03,  1.405e+03,  1.406e+03,
        1.407e+03,  1.408e+03,  1.409e+03,  1.411e+03,  1.412e+03,
        1.413e+03,  1.414e+03,  1.415e+03,  1.416e+03,  1.417e+03,
        1.418e+03,  1.419e+03,  1.421e+03,  1.422e+03,  1.423e+03,
        1.424e+03,  1.425e+03,  1.426e+03,  1.427e+03,  1.428e+03,
        1.429e+03,  1.431e+03,  1.432e+03,  1.433e+03,  1.434e+03,
        1.435e+03,  1.436e+03,  1.437e+03,  1.438e+03,  1.439e+03,
        1.441e+03,  1.442e+03,  1.443e+03,  1.444e+03,  1.445e+03,
        1.446e+03,  1.447e+03,  1.448e+03,  1.449e+03,  1.451e+03,
        1.452e+03,  1.453e+03,  1.454e+03,  1.455e+03,  1.456e+03,
        1.457e+03,  1.458e+03,  1.459e+03,  1.461e+03,  1.462e+03,
        1.463e+03,  1.464e+03,  1.465e+03,  1.466e+03,  1.467e+03,
        1.468e+03,  1.469e+03,  1.471e+03,  1.472e+03,  1.473e+03,
        1.474e+03,  1.475e+03,  1.476e+03,  1.477e+03,  1.478e+03,
        1.479e+03,  1.481e+03,  1.482e+03,  1.483e+03,  1.484e+03,
        1.485e+03,  1.486e+03,  1.487e+03,  1.488e+03,  1.489e+03,
        1.491e+03,  1.492e+03,  1.493e+03,  1.494e+03,  1.495e+03,
        1.496e+03,  1.497e+03,  1.498e+03,  1.499e+03,  1.501e+03,
        1.502e+03,  1.503e+03,  1.504e+03,  1.505e+03,  1.506e+03,
        1.507e+03,  1.508e+03,  1.509e+03,  1.511e+03,  1.512e+03,
        1.513e+03,  1.514e+03,  1.515e+03,  1.516e+03,  1.517e+03,
        1.518e+03,  1.519e+03,  1.521e+03,  1.522e+03,  1.523e+03,
        1.524e+03,  1.525e+03,  1.526e+03,  1.527e+03,  1.528e+03,
        1.529e+03,  1.531e+03,  1.532e+03,  1.533e+03,  1.534e+03,
        1.535e+03,  1.536e+03,  1.537e+03,  1.538e+03,  1.539e+03,
        1.541e+03,  1.542e+03,  1.543e+03,  1.544e+03,  1.545e+03,
        1.546e+03,  1.547e+03,  1.548e+03,  1.549e+03,  1.551e+03,
        1.552e+03,  1.553e+03,  1.554e+03,  1.555e+03,  1.556e+03,
        1.557e+03,  1.558e+03,  1.559e+03,  1.561e+03,  1.562e+03,
        1.563e+03,  1.564e+03,  1.565e+03,  1.566e+03,  1.567e+03,
        1.568e+03,  1.569e+03,  1.571e+03,  1.572e+03,  1.573e+03,
        1.574e+03,  1.575e+03,  1.576e+03,  1.577e+03,  1.578e+03,
        1.579e+03,  1.581e+03,  1.582e+03,  1.583e+03,  1.584e+03,
        1.585e+03,  1.586e+03,  1.587e+03,  1.588e+03,  1.589e+03,
        1.591e+03,  1.592e+03,  1.593e+03,  1.594e+03,  1.595e+03,
        1.596e+03,  1.597e+03,  1.598e+03,  1.599e+03,  1.601e+03,
        1.602e+03,  1.603e+03,  1.604e+03,  1.605e+03,  1.606e+03,
        1.607e+03,  1.608e+03,  1.609e+03,  1.611e+03,  1.612e+03,
        1.613e+03,  1.614e+03,  1.615e+03,  1.616e+03,  1.617e+03,
        1.618e+03,  1.619e+03,  1.621e+03,  1.622e+03,  1.623e+03,
        1.624e+03,  1.625e+03,  1.626e+03,  1.627e+03,  1.628e+03,
        1.629e+03,  1.630e+03,  1.631e+03,  1.632e+03,  1.633e+03,
        1.634e+03,  1.635e+03,  1.636e+03,  1.637e+03,  1.638e+03,
        1.639e+03,  1.640e+03,  1.641e+03,  1.642e+03,  1.643e+03,
        1.644e+03,  1.645e+03,  1.646e+03,  1.647e+03,  1.648e+03,
        1.649e+03,  1.651e+03,  1.652e+03,  1.653e+03,  1.654e+03,
        1.655e+03,  1.656e+03,  1.657e+03,  1.658e+03,  1.659e+03,
        1.660e+03,  1.662e+03,  1.663e+03,  1.664e+03,  1.665e+03,
        1.666e+03,  1.667e+03,  1.668e+03,  1.669e+03,  1.670e+03,
        1.671e+03,  1.672e+03,  1.673e+03,  1.674e+03,  1.675e+03,
        1.676e+03,  1.677e+03,  1.678e+03,  1.679e+03,  1.680e+03,
        1.681e+03,  1.682e+03,  1.683e+03,  1.684e+03,  1.686e+03,
        1.687e+03,  1.688e+03,  1.689e+03,  1.691e+03,  1.692e+03,
        1.693e+03,  1.694e+03,  1.695e+03,  1.696e+03,  1.697e+03,
        1.698e+03,  1.699e+03,  1.701e+03,  1.702e+03,  1.703e+03,
        1.704e+03,  1.705e+03,  1.706e+03,  1.707e+03,  1.708e+03,
        1.709e+03,  1.711e+03,  1.712e+03,  1.713e+03,  1.714e+03,
        1.715e+03,  1.716e+03,  1.717e+03,  1.718e+03,  1.719e+03,
        1.721e+03,  1.722e+03,  1.723e+03,  1.725e+03,  1.726e+03,
        1.727e+03,  1.728e+03,  1.729e+03,  1.731e+03,  1.732e+03,
        1.733e+03,  1.734e+03,  1.735e+03,  1.736e+03,  1.737e+03,
        1.738e+03,  1.739e+03,  1.741e+03,  1.742e+03,  1.743e+03,
        1.744e+03,  1.745e+03,  1.746e+03,  1.747e+03,  1.748e+03,
        1.749e+03,  1.751e+03,  1.752e+03,  1.753e+03,  1.754e+03,
        1.756e+03,  1.757e+03,  1.758e+03,  1.759e+03,  1.761e+03,
        1.762e+03,  1.763e+03,  1.764e+03,  1.767e+03,  1.768e+03,
        1.769e+03,  1.771e+03,  1.772e+03,  1.773e+03,  1.774e+03,
        1.776e+03,  1.777e+03,  1.778e+03,  1.779e+03,  1.781e+03,
        1.782e+03,  1.783e+03,  1.784e+03,  1.786e+03,  1.787e+03,
        1.788e+03,  1.789e+03,  1.791e+03,  1.793e+03,  1.794e+03,
        1.796e+03,  1.797e+03,  1.798e+03,  1.799e+03,  1.252e+03,
        1.253e+03,  1.254e+03,  1.255e+03,  1.256e+03,  1.257e+03,
        1.258e+03,  1.259e+03,  1.260e+03,  1.261e+03,  1.262e+03,
        1.263e+03,  1.264e+03,  1.265e+03,  1.266e+03,  1.267e+03,
        1.268e+03,  1.269e+03,  1.270e+03,  1.271e+03,  1.272e+03,
        1.273e+03,  1.274e+03,  1.275e+03,  1.276e+03,  1.277e+03,
        1.278e+03,  1.279e+03])

In [22]:
Life_Exp.drop(['Code_x','Population (historical estimates)_x'],inplace=True,axis=1)

In [23]:
Life_Exp.head()

,Entity,Code,Year,"Life expectancy at birth, total (years)","Health expenditure per capita, PPP (constant 2011 international $)",Population (historical estimates),Continent,Life satisfaction in Cantril Ladder (World Happiness Report 2021),$1.90 per day - share of population below poverty line,Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015.0,NaN,NaN,NaN,Asia,0.000,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1960.0,32.292,NaN,8996967.0,NaN,3.983,0.0,32.446,1326.0,0.0
2,Afghanistan,AFG,1961.0,32.742,NaN,9169406.0,NaN,3.983,0.0,32.962,1309.0,0.0
3,Afghanistan,AFG,1962.0,33.185,NaN,9351442.0,NaN,3.983,0.0,33.471,1302.0,0.0
4,Afghanistan,AFG,1963.0,33.624,NaN,9543200.0,NaN,3.983,0.0,33.971,1298.0,0.0

In [24]:
Life_Exp=Life_Exp.fillna(0)
Life_Exp.head()

,Entity,Code,Year,"Life expectancy at birth, total (years)","Health expenditure per capita, PPP (constant 2011 international $)",Population (historical estimates),Continent,Life satisfaction in Cantril Ladder (World Happiness Report 2021),$1.90 per day - share of population below poverty line,Life expectancy,GDP per capita,$3.20 per day - share of population below poverty line
0,Abkhazia,OWID_ABK,2015.0,0.000,0.0,0.0,Asia,0.000,0.0,0.000,0.0,0.0
1,Afghanistan,AFG,1960.0,32.292,0.0,8996967.0,0,3.983,0.0,32.446,1326.0,0.0
2,Afghanistan,AFG,1961.0,32.742,0.0,9169406.0,0,3.983,0.0,32.962,1309.0,0.0
3,Afghanistan,AFG,1962.0,33.185,0.0,9351442.0,0,3.983,0.0,33.471,1302.0,0.0
4,Afghanistan,AFG,1963.0,33.624,0.0,9543200.0,0,3.983,0.0,33.971,1298.0,0.0

In [25]:
data6= pd.read_csv('food-supply-vs-life-expectancy.csv')
Life_Exp= pd.merge(data6, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

(66055, 17)

In [26]:
Life_Exp.nunique()

Entity                                                                                                                            403
Code_x                                                                                                                            287
Year                                                                                                                              797
Estimates, 1950 - 2020: Annually interpolated demographic indicators - Life expectancy at birth, both sexes combined (years)    14206
Daily caloric supply (OWID based on UN FAO & historical sources)                                                                 2735
Population (historical estimates)_x                                                                                             51142
Continent_x                                                                                                                         7
Code_y                                                                                                                            287
Life expectancy at birth, total (years)                                                                                         12562
Health expenditure per capita, PPP (constant 2011 international $)                                                               4619
Population (historical estimates)_y                                                                                             51143
Continent_y                                                                                                                         8
Life satisfaction in Cantril Ladder (World Happiness Report 2021)                                                                 154
$1.90 per day - share of population below poverty line                                                                           6084
Life expectancy                                                                                                                 15301
GDP per capita                                                                                                                  11344
$3.20 per day - share of population below poverty line                                                                           6405
dtype: int64

In [27]:
Life_Exp.Year.unique()

array([ 2.015e+03,  1.950e+03,  1.951e+03,  1.952e+03,  1.953e+03,
        1.954e+03,  1.955e+03,  1.956e+03,  1.957e+03,  1.958e+03,
        1.959e+03,  1.960e+03,  1.961e+03,  1.962e+03,  1.963e+03,
        1.964e+03,  1.965e+03,  1.966e+03,  1.967e+03,  1.968e+03,
        1.969e+03,  1.970e+03,  1.971e+03,  1.972e+03,  1.973e+03,
        1.974e+03,  1.975e+03,  1.976e+03,  1.977e+03,  1.978e+03,
        1.979e+03,  1.980e+03,  1.981e+03,  1.982e+03,  1.983e+03,
        1.984e+03,  1.985e+03,  1.986e+03,  1.987e+03,  1.988e+03,
        1.989e+03,  1.990e+03,  1.991e+03,  1.992e+03,  1.993e+03,
        1.994e+03,  1.995e+03,  1.996e+03,  1.997e+03,  1.998e+03,
        1.999e+03,  2.000e+03,  2.001e+03,  2.002e+03,  2.003e+03,
        2.004e+03,  2.005e+03,  2.006e+03,  2.007e+03,  2.008e+03,
        2.009e+03,  2.010e+03,  2.011e+03,  2.012e+03,  2.013e+03,
        2.014e+03,  2.016e+03,  2.017e+03,  2.018e+03,  2.019e+03,
        2.020e+03, -1.000e+04, -9.000e+03, -8.000e+03, -7.000e+03,
       -6.000e+03, -5.000e+03, -4.000e+03, -3.000e+03, -2.000e+03,
       -1.000e+03,  0.000e+00,  1.000e+02,  2.000e+02,  3.000e+02,
        4.000e+02,  5.000e+02,  6.000e+02,  7.000e+02,  8.000e+02,
        9.000e+02,  1.000e+03,  1.100e+03,  1.200e+03,  1.300e+03,
        1.400e+03,  1.500e+03,  1.600e+03,  1.700e+03,  1.710e+03,
        1.720e+03,  1.730e+03,  1.740e+03,  1.750e+03,  1.760e+03,
        1.770e+03,  1.780e+03,  1.790e+03,  1.800e+03,  1.801e+03,
        1.802e+03,  1.803e+03,  1.804e+03,  1.805e+03,  1.806e+03,
        1.807e+03,  1.808e+03,  1.809e+03,  1.810e+03,  1.811e+03,
        1.812e+03,  1.813e+03,  1.814e+03,  1.815e+03,  1.816e+03,
        1.817e+03,  1.818e+03,  1.819e+03,  1.820e+03,  1.821e+03,
        1.822e+03,  1.823e+03,  1.824e+03,  1.825e+03,  1.826e+03,
        1.827e+03,  1.828e+03,  1.829e+03,  1.830e+03,  1.831e+03,
        1.832e+03,  1.833e+03,  1.834e+03,  1.835e+03,  1.836e+03,
        1.837e+03,  1.838e+03,  1.839e+03,  1.840e+03,  1.841e+03,
        1.842e+03,  1.843e+03,  1.844e+03,  1.845e+03,  1.846e+03,
        1.847e+03,  1.848e+03,  1.849e+03,  1.850e+03,  1.851e+03,
        1.852e+03,  1.853e+03,  1.854e+03,  1.855e+03,  1.856e+03,
        1.857e+03,  1.858e+03,  1.859e+03,  1.860e+03,  1.861e+03,
        1.862e+03,  1.863e+03,  1.864e+03,  1.865e+03,  1.866e+03,
        1.867e+03,  1.868e+03,  1.869e+03,  1.870e+03,  1.871e+03,
        1.872e+03,  1.873e+03,  1.874e+03,  1.875e+03,  1.876e+03,
        1.877e+03,  1.878e+03,  1.879e+03,  1.880e+03,  1.881e+03,
        1.882e+03,  1.883e+03,  1.884e+03,  1.885e+03,  1.886e+03,
        1.887e+03,  1.888e+03,  1.889e+03,  1.890e+03,  1.891e+03,
        1.892e+03,  1.893e+03,  1.894e+03,  1.895e+03,  1.896e+03,
        1.897e+03,  1.898e+03,  1.899e+03,  1.900e+03,  1.901e+03,
        1.902e+03,  1.903e+03,  1.904e+03,  1.905e+03,  1.906e+03,
        1.907e+03,  1.908e+03,  1.909e+03,  1.910e+03,  1.911e+03,
        1.912e+03,  1.913e+03,  1.914e+03,  1.915e+03,  1.916e+03,
        1.917e+03,  1.918e+03,  1.919e+03,  1.920e+03,  1.921e+03,
        1.922e+03,  1.923e+03,  1.924e+03,  1.925e+03,  1.926e+03,
        1.927e+03,  1.928e+03,  1.929e+03,  1.930e+03,  1.931e+03,
        1.932e+03,  1.933e+03,  1.934e+03,  1.935e+03,  1.936e+03,
        1.937e+03,  1.938e+03,  1.939e+03,  1.940e+03,  1.941e+03,
        1.942e+03,  1.943e+03,  1.944e+03,  1.945e+03,  1.946e+03,
        1.947e+03,  1.948e+03,  1.949e+03,  2.021e+03,  1.705e+03,
        1.270e+03,  1.310e+03,  1.380e+03,  1.420e+03,  1.450e+03,
        1.000e+00,  1.550e+03,  1.650e+03,  1.090e+03,  1.120e+03,
        1.410e+03,  1.430e+03,  1.440e+03,  1.460e+03,  1.470e+03,
        1.480e+03,  1.490e+03,  1.510e+03,  1.520e+03,  1.530e+03,
        1.540e+03,  1.560e+03,  1.570e+03,  1.580e+03,  1.590e+03,
        1.610e+03,  1.620e+03,  1.661e+03,  1.685e+03,  1.690e+03,
        1.724e+03,  1.766e+03,  1.775e+03,  1.792e+03,  7.300e+02,
        1.280e+03,  1.755e+03,  1.765e+03,  1.785e+03,  1.795e+03,
        1.281e+03,  1.282e+03,  1.283e+03,  1.284e+03,  1.285e+03,
        1.286e+03,  1.287e+03,  1.288e+03,  1.289e+03,  1.290e+03,
        1.291e+03,  1.292e+03,  1.293e+03,  1.294e+03,  1.295e+03,
        1.296e+03,  1.297e+03,  1.298e+03,  1.299e+03,  1.301e+03,
        1.302e+03,  1.303e+03,  1.304e+03,  1.305e+03,  1.306e+03,
        1.307e+03,  1.308e+03,  1.309e+03,  1.311e+03,  1.312e+03,
        1.313e+03,  1.314e+03,  1.315e+03,  1.316e+03,  1.317e+03,
        1.318e+03,  1.319e+03,  1.320e+03,  1.321e+03,  1.322e+03,
        1.323e+03,  1.324e+03,  1.325e+03,  1.326e+03,  1.327e+03,
        1.328e+03,  1.329e+03,  1.330e+03,  1.331e+03,  1.332e+03,
        1.333e+03,  1.334e+03,  1.335e+03,  1.336e+03,  1.337e+03,
        1.338e+03,  1.339e+03,  1.340e+03,  1.341e+03,  1.342e+03,
        1.343e+03,  1.344e+03,  1.345e+03,  1.346e+03,  1.347e+03,
        1.348e+03,  1.349e+03,  1.350e+03,  1.351e+03,  1.352e+03,
        1.353e+03,  1.354e+03,  1.355e+03,  1.356e+03,  1.357e+03,
        1.358e+03,  1.359e+03,  1.360e+03,  1.361e+03,  1.362e+03,
        1.363e+03,  1.364e+03,  1.365e+03,  1.366e+03,  1.367e+03,
        1.368e+03,  1.369e+03,  1.370e+03,  1.371e+03,  1.372e+03,
        1.373e+03,  1.374e+03,  1.375e+03,  1.376e+03,  1.377e+03,
        1.378e+03,  1.379e+03,  1.381e+03,  1.382e+03,  1.383e+03,
        1.384e+03,  1.385e+03,  1.386e+03,  1.387e+03,  1.388e+03,
        1.389e+03,  1.390e+03,  1.391e+03,  1.392e+03,  1.393e+03,
        1.394e+03,  1.395e+03,  1.396e+03,  1.397e+03,  1.398e+03,
        1.399e+03,  1.401e+03,  1.402e+03,  1.403e+03,  1.404e+03,
        1.405e+03,  1.406e+03,  1.407e+03,  1.408e+03,  1.409e+03,
        1.411e+03,  1.412e+03,  1.413e+03,  1.414e+03,  1.415e+03,
        1.416e+03,  1.417e+03,  1.418e+03,  1.419e+03,  1.421e+03,
        1.422e+03,  1.423e+03,  1.424e+03,  1.425e+03,  1.426e+03,
        1.427e+03,  1.428e+03,  1.429e+03,  1.431e+03,  1.432e+03,
        1.433e+03,  1.434e+03,  1.435e+03,  1.436e+03,  1.437e+03,
        1.438e+03,  1.439e+03,  1.441e+03,  1.442e+03,  1.443e+03,
        1.444e+03,  1.445e+03,  1.446e+03,  1.447e+03,  1.448e+03,
        1.449e+03,  1.451e+03,  1.452e+03,  1.453e+03,  1.454e+03,
        1.455e+03,  1.456e+03,  1.457e+03,  1.458e+03,  1.459e+03,
        1.461e+03,  1.462e+03,  1.463e+03,  1.464e+03,  1.465e+03,
        1.466e+03,  1.467e+03,  1.468e+03,  1.469e+03,  1.471e+03,
        1.472e+03,  1.473e+03,  1.474e+03,  1.475e+03,  1.476e+03,
        1.477e+03,  1.478e+03,  1.479e+03,  1.481e+03,  1.482e+03,
        1.483e+03,  1.484e+03,  1.485e+03,  1.486e+03,  1.487e+03,
        1.488e+03,  1.489e+03,  1.491e+03,  1.492e+03,  1.493e+03,
        1.494e+03,  1.495e+03,  1.496e+03,  1.497e+03,  1.498e+03,
        1.499e+03,  1.501e+03,  1.502e+03,  1.503e+03,  1.504e+03,
        1.505e+03,  1.506e+03,  1.507e+03,  1.508e+03,  1.509e+03,
        1.511e+03,  1.512e+03,  1.513e+03,  1.514e+03,  1.515e+03,
        1.516e+03,  1.517e+03,  1.518e+03,  1.519e+03,  1.521e+03,
        1.522e+03,  1.523e+03,  1.524e+03,  1.525e+03,  1.526e+03,
        1.527e+03,  1.528e+03,  1.529e+03,  1.531e+03,  1.532e+03,
        1.533e+03,  1.534e+03,  1.535e+03,  1.536e+03,  1.537e+03,
        1.538e+03,  1.539e+03,  1.541e+03,  1.542e+03,  1.543e+03,
        1.544e+03,  1.545e+03,  1.546e+03,  1.547e+03,  1.548e+03,
        1.549e+03,  1.551e+03,  1.552e+03,  1.553e+03,  1.554e+03,
        1.555e+03,  1.556e+03,  1.557e+03,  1.558e+03,  1.559e+03,
        1.561e+03,  1.562e+03,  1.563e+03,  1.564e+03,  1.565e+03,
        1.566e+03,  1.567e+03,  1.568e+03,  1.569e+03,  1.571e+03,
        1.572e+03,  1.573e+03,  1.574e+03,  1.575e+03,  1.576e+03,
        1.577e+03,  1.578e+03,  1.579e+03,  1.581e+03,  1.582e+03,
        1.583e+03,  1.584e+03,  1.585e+03,  1.586e+03,  1.587e+03,
        1.588e+03,  1.589e+03,  1.591e+03,  1.592e+03,  1.593e+03,
        1.594e+03,  1.595e+03,  1.596e+03,  1.597e+03,  1.598e+03,
        1.599e+03,  1.601e+03,  1.602e+03,  1.603e+03,  1.604e+03,
        1.605e+03,  1.606e+03,  1.607e+03,  1.608e+03,  1.609e+03,
        1.611e+03,  1.612e+03,  1.613e+03,  1.614e+03,  1.615e+03,
        1.616e+03,  1.617e+03,  1.618e+03,  1.619e+03,  1.621e+03,
        1.622e+03,  1.623e+03,  1.624e+03,  1.625e+03,  1.626e+03,
        1.627e+03,  1.628e+03,  1.629e+03,  1.630e+03,  1.631e+03,
        1.632e+03,  1.633e+03,  1.634e+03,  1.635e+03,  1.636e+03,
        1.637e+03,  1.638e+03,  1.639e+03,  1.640e+03,  1.641e+03,
        1.642e+03,  1.643e+03,  1.644e+03,  1.645e+03,  1.646e+03,
        1.647e+03,  1.648e+03,  1.649e+03,  1.651e+03,  1.652e+03,
        1.653e+03,  1.654e+03,  1.655e+03,  1.656e+03,  1.657e+03,
        1.658e+03,  1.659e+03,  1.660e+03,  1.662e+03,  1.663e+03,
        1.664e+03,  1.665e+03,  1.666e+03,  1.667e+03,  1.668e+03,
        1.669e+03,  1.670e+03,  1.671e+03,  1.672e+03,  1.673e+03,
        1.674e+03,  1.675e+03,  1.676e+03,  1.677e+03,  1.678e+03,
        1.679e+03,  1.680e+03,  1.681e+03,  1.682e+03,  1.683e+03,
        1.684e+03,  1.686e+03,  1.687e+03,  1.688e+03,  1.689e+03,
        1.691e+03,  1.692e+03,  1.693e+03,  1.694e+03,  1.695e+03,
        1.696e+03,  1.697e+03,  1.698e+03,  1.699e+03,  1.701e+03,
        1.702e+03,  1.703e+03,  1.704e+03,  1.706e+03,  1.707e+03,
        1.708e+03,  1.709e+03,  1.711e+03,  1.712e+03,  1.713e+03,
        1.714e+03,  1.715e+03,  1.716e+03,  1.717e+03,  1.718e+03,
        1.719e+03,  1.721e+03,  1.722e+03,  1.723e+03,  1.725e+03,
        1.726e+03,  1.727e+03,  1.728e+03,  1.729e+03,  1.731e+03,
        1.732e+03,  1.733e+03,  1.734e+03,  1.735e+03,  1.736e+03,
        1.737e+03,  1.738e+03,  1.739e+03,  1.741e+03,  1.742e+03,
        1.743e+03,  1.744e+03,  1.745e+03,  1.746e+03,  1.747e+03,
        1.748e+03,  1.749e+03,  1.751e+03,  1.752e+03,  1.753e+03,
        1.754e+03,  1.756e+03,  1.757e+03,  1.758e+03,  1.759e+03,
        1.761e+03,  1.762e+03,  1.763e+03,  1.764e+03,  1.767e+03,
        1.768e+03,  1.769e+03,  1.771e+03,  1.772e+03,  1.773e+03,
        1.774e+03,  1.776e+03,  1.777e+03,  1.778e+03,  1.779e+03,
        1.781e+03,  1.782e+03,  1.783e+03,  1.784e+03,  1.786e+03,
        1.787e+03,  1.788e+03,  1.789e+03,  1.791e+03,  1.793e+03,
        1.794e+03,  1.796e+03,  1.797e+03,  1.798e+03,  1.799e+03,
        1.252e+03,  1.253e+03,  1.254e+03,  1.255e+03,  1.256e+03,
        1.257e+03,  1.258e+03,  1.259e+03,  1.260e+03,  1.261e+03,
        1.262e+03,  1.263e+03,  1.264e+03,  1.265e+03,  1.266e+03,
        1.267e+03,  1.268e+03,  1.269e+03,  1.271e+03,  1.272e+03,
        1.273e+03,  1.274e+03,  1.275e+03,  1.276e+03,  1.277e+03,
        1.278e+03,  1.279e+03])

In [28]:
Life_Exp.drop(['Estimates, 1950 - 2020: Annually interpolated demographic indicators - Life expectancy at birth, both sexes combined (years)','Life expectancy at birth, total (years)','Population (historical estimates)_y','Continent_y','Continent_x','Code_y'],inplace=True,axis=1)

In [29]:
Life_Exp.nunique()

Entity                                                                  403
Code_x                                                                  287
Year                                                                    797
Daily caloric supply (OWID based on UN FAO & historical sources)       2735
Population (historical estimates)_x                                   51142
Health expenditure per capita, PPP (constant 2011 international $)     4619
Life satisfaction in Cantril Ladder (World Happiness Report 2021)       154
$1.90 per day - share of population below poverty line                 6084
Life expectancy                                                       15301
GDP per capita                                                        11344
$3.20 per day - share of population below poverty line                 6405
dtype: int64

In [30]:
Life_Exp.rename(columns = {'Daily caloric supply (OWID based on UN FAO & historical sources)':'Daily Calorie Intake','Population (historical estimates)_x':'Population','Health expenditure per capita, PPP (constant 2011 international $)':'Health expenditure per capita','Life satisfaction in Cantril Ladder (World Happiness Report 2021)':'World Happiness Index','$1.90 per day - share of population below poverty line':'$1.90_PER_DAY_BPL','$3.20 per day - share of population below poverty line':'$3.20_PER_DAY_BPL'}, inplace = True)

In [31]:
Life_Exp.nunique()

Entity                             403
Code_x                             287
Year                               797
Daily Calorie Intake              2735
Population                       51142
Health expenditure per capita     4619
World Happiness Index              154
$1.90_PER_DAY_BPL                 6084
Life expectancy                  15301
GDP per capita                   11344
$3.20_PER_DAY_BPL                 6405
dtype: int64

In [32]:
data7= pd.read_csv('number-of-deaths-by-risk-factor.csv')
Life_Exp= pd.merge(data7, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

(67663, 40)

In [33]:
Life_Exp.nunique()

Entity                                                                                                                455
Code                                                                                                                  205
Year                                                                                                                  797
Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)                 5768
Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)                 6950
Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)                          4992
Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)                     5472
Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)                                  5641
Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)                           4680
Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)                          4092
Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)                             4989
Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)                             5214
Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)                                4689
Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)                                   4735
Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)                   4043
Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)     4958
Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)                       4354
Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)                        4498
Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)                                      6520
Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)                  6618
Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)                                6516
Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)                         6416
Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)                            3860
Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)            4046
Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)                                     3667
Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)                     3766
Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)                         2151
Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)                               3314
Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)                   1578
Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)                  3314
Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)                              2030
Code_x                                                                                                                287
Daily Calorie Intake                                                                                                 2735
Population                                                                                                          51142
Health expenditure per capita                                                                                        4619
World Happiness Index                                                                                                 154
$1.90_PER_DAY_BPL                                                                                                    6084
Life expectancy                                                                                                     15301
GDP per capita                                                                                                      11344
$3.20_PER_DAY_BPL                                                                                                    6405
dtype: int64

In [34]:
Life_Exp.Year.unique()

array([ 1.990e+03,  1.991e+03,  1.992e+03,  1.993e+03,  1.994e+03,
        1.995e+03,  1.996e+03,  1.997e+03,  1.998e+03,  1.999e+03,
        2.000e+03,  2.001e+03,  2.002e+03,  2.003e+03,  2.004e+03,
        2.005e+03,  2.006e+03,  2.007e+03,  2.008e+03,  2.009e+03,
        2.010e+03,  2.011e+03,  2.012e+03,  2.013e+03,  2.014e+03,
        2.015e+03,  2.016e+03,  2.017e+03,  2.018e+03,  2.019e+03,
        1.950e+03,  1.951e+03,  1.952e+03,  1.953e+03,  1.954e+03,
        1.955e+03,  1.956e+03,  1.957e+03,  1.958e+03,  1.959e+03,
        1.960e+03,  1.961e+03,  1.962e+03,  1.963e+03,  1.964e+03,
        1.965e+03,  1.966e+03,  1.967e+03,  1.968e+03,  1.969e+03,
        1.970e+03,  1.971e+03,  1.972e+03,  1.973e+03,  1.974e+03,
        1.975e+03,  1.976e+03,  1.977e+03,  1.978e+03,  1.979e+03,
        1.980e+03,  1.981e+03,  1.982e+03,  1.983e+03,  1.984e+03,
        1.985e+03,  1.986e+03,  1.987e+03,  1.988e+03,  1.989e+03,
        2.020e+03, -1.000e+04, -9.000e+03, -8.000e+03, -7.000e+03,
       -6.000e+03, -5.000e+03, -4.000e+03, -3.000e+03, -2.000e+03,
       -1.000e+03,  0.000e+00,  1.000e+02,  2.000e+02,  3.000e+02,
        4.000e+02,  5.000e+02,  6.000e+02,  7.000e+02,  8.000e+02,
        9.000e+02,  1.000e+03,  1.100e+03,  1.200e+03,  1.300e+03,
        1.400e+03,  1.500e+03,  1.600e+03,  1.700e+03,  1.710e+03,
        1.720e+03,  1.730e+03,  1.740e+03,  1.750e+03,  1.760e+03,
        1.770e+03,  1.780e+03,  1.790e+03,  1.800e+03,  1.801e+03,
        1.802e+03,  1.803e+03,  1.804e+03,  1.805e+03,  1.806e+03,
        1.807e+03,  1.808e+03,  1.809e+03,  1.810e+03,  1.811e+03,
        1.812e+03,  1.813e+03,  1.814e+03,  1.815e+03,  1.816e+03,
        1.817e+03,  1.818e+03,  1.819e+03,  1.820e+03,  1.821e+03,
        1.822e+03,  1.823e+03,  1.824e+03,  1.825e+03,  1.826e+03,
        1.827e+03,  1.828e+03,  1.829e+03,  1.830e+03,  1.831e+03,
        1.832e+03,  1.833e+03,  1.834e+03,  1.835e+03,  1.836e+03,
        1.837e+03,  1.838e+03,  1.839e+03,  1.840e+03,  1.841e+03,
        1.842e+03,  1.843e+03,  1.844e+03,  1.845e+03,  1.846e+03,
        1.847e+03,  1.848e+03,  1.849e+03,  1.850e+03,  1.851e+03,
        1.852e+03,  1.853e+03,  1.854e+03,  1.855e+03,  1.856e+03,
        1.857e+03,  1.858e+03,  1.859e+03,  1.860e+03,  1.861e+03,
        1.862e+03,  1.863e+03,  1.864e+03,  1.865e+03,  1.866e+03,
        1.867e+03,  1.868e+03,  1.869e+03,  1.870e+03,  1.871e+03,
        1.872e+03,  1.873e+03,  1.874e+03,  1.875e+03,  1.876e+03,
        1.877e+03,  1.878e+03,  1.879e+03,  1.880e+03,  1.881e+03,
        1.882e+03,  1.883e+03,  1.884e+03,  1.885e+03,  1.886e+03,
        1.887e+03,  1.888e+03,  1.889e+03,  1.890e+03,  1.891e+03,
        1.892e+03,  1.893e+03,  1.894e+03,  1.895e+03,  1.896e+03,
        1.897e+03,  1.898e+03,  1.899e+03,  1.900e+03,  1.901e+03,
        1.902e+03,  1.903e+03,  1.904e+03,  1.905e+03,  1.906e+03,
        1.907e+03,  1.908e+03,  1.909e+03,  1.910e+03,  1.911e+03,
        1.912e+03,  1.913e+03,  1.914e+03,  1.915e+03,  1.916e+03,
        1.917e+03,  1.918e+03,  1.919e+03,  1.920e+03,  1.921e+03,
        1.922e+03,  1.923e+03,  1.924e+03,  1.925e+03,  1.926e+03,
        1.927e+03,  1.928e+03,  1.929e+03,  1.930e+03,  1.931e+03,
        1.932e+03,  1.933e+03,  1.934e+03,  1.935e+03,  1.936e+03,
        1.937e+03,  1.938e+03,  1.939e+03,  1.940e+03,  1.941e+03,
        1.942e+03,  1.943e+03,  1.944e+03,  1.945e+03,  1.946e+03,
        1.947e+03,  1.948e+03,  1.949e+03,  2.021e+03,  1.705e+03,
        1.270e+03,  1.310e+03,  1.380e+03,  1.420e+03,  1.450e+03,
        1.000e+00,  1.550e+03,  1.650e+03,  1.090e+03,  1.120e+03,
        1.410e+03,  1.430e+03,  1.440e+03,  1.460e+03,  1.470e+03,
        1.480e+03,  1.490e+03,  1.510e+03,  1.520e+03,  1.530e+03,
        1.540e+03,  1.560e+03,  1.570e+03,  1.580e+03,  1.590e+03,
        1.610e+03,  1.620e+03,  1.661e+03,  1.685e+03,  1.690e+03,
        1.724e+03,  1.766e+03,  1.775e+03,  1.792e+03,  7.300e+02,
        1.280e+03,  1.755e+03,  1.765e+03,  1.785e+03,  1.795e+03,
        1.281e+03,  1.282e+03,  1.283e+03,  1.284e+03,  1.285e+03,
        1.286e+03,  1.287e+03,  1.288e+03,  1.289e+03,  1.290e+03,
        1.291e+03,  1.292e+03,  1.293e+03,  1.294e+03,  1.295e+03,
        1.296e+03,  1.297e+03,  1.298e+03,  1.299e+03,  1.301e+03,
        1.302e+03,  1.303e+03,  1.304e+03,  1.305e+03,  1.306e+03,
        1.307e+03,  1.308e+03,  1.309e+03,  1.311e+03,  1.312e+03,
        1.313e+03,  1.314e+03,  1.315e+03,  1.316e+03,  1.317e+03,
        1.318e+03,  1.319e+03,  1.320e+03,  1.321e+03,  1.322e+03,
        1.323e+03,  1.324e+03,  1.325e+03,  1.326e+03,  1.327e+03,
        1.328e+03,  1.329e+03,  1.330e+03,  1.331e+03,  1.332e+03,
        1.333e+03,  1.334e+03,  1.335e+03,  1.336e+03,  1.337e+03,
        1.338e+03,  1.339e+03,  1.340e+03,  1.341e+03,  1.342e+03,
        1.343e+03,  1.344e+03,  1.345e+03,  1.346e+03,  1.347e+03,
        1.348e+03,  1.349e+03,  1.350e+03,  1.351e+03,  1.352e+03,
        1.353e+03,  1.354e+03,  1.355e+03,  1.356e+03,  1.357e+03,
        1.358e+03,  1.359e+03,  1.360e+03,  1.361e+03,  1.362e+03,
        1.363e+03,  1.364e+03,  1.365e+03,  1.366e+03,  1.367e+03,
        1.368e+03,  1.369e+03,  1.370e+03,  1.371e+03,  1.372e+03,
        1.373e+03,  1.374e+03,  1.375e+03,  1.376e+03,  1.377e+03,
        1.378e+03,  1.379e+03,  1.381e+03,  1.382e+03,  1.383e+03,
        1.384e+03,  1.385e+03,  1.386e+03,  1.387e+03,  1.388e+03,
        1.389e+03,  1.390e+03,  1.391e+03,  1.392e+03,  1.393e+03,
        1.394e+03,  1.395e+03,  1.396e+03,  1.397e+03,  1.398e+03,
        1.399e+03,  1.401e+03,  1.402e+03,  1.403e+03,  1.404e+03,
        1.405e+03,  1.406e+03,  1.407e+03,  1.408e+03,  1.409e+03,
        1.411e+03,  1.412e+03,  1.413e+03,  1.414e+03,  1.415e+03,
        1.416e+03,  1.417e+03,  1.418e+03,  1.419e+03,  1.421e+03,
        1.422e+03,  1.423e+03,  1.424e+03,  1.425e+03,  1.426e+03,
        1.427e+03,  1.428e+03,  1.429e+03,  1.431e+03,  1.432e+03,
        1.433e+03,  1.434e+03,  1.435e+03,  1.436e+03,  1.437e+03,
        1.438e+03,  1.439e+03,  1.441e+03,  1.442e+03,  1.443e+03,
        1.444e+03,  1.445e+03,  1.446e+03,  1.447e+03,  1.448e+03,
        1.449e+03,  1.451e+03,  1.452e+03,  1.453e+03,  1.454e+03,
        1.455e+03,  1.456e+03,  1.457e+03,  1.458e+03,  1.459e+03,
        1.461e+03,  1.462e+03,  1.463e+03,  1.464e+03,  1.465e+03,
        1.466e+03,  1.467e+03,  1.468e+03,  1.469e+03,  1.471e+03,
        1.472e+03,  1.473e+03,  1.474e+03,  1.475e+03,  1.476e+03,
        1.477e+03,  1.478e+03,  1.479e+03,  1.481e+03,  1.482e+03,
        1.483e+03,  1.484e+03,  1.485e+03,  1.486e+03,  1.487e+03,
        1.488e+03,  1.489e+03,  1.491e+03,  1.492e+03,  1.493e+03,
        1.494e+03,  1.495e+03,  1.496e+03,  1.497e+03,  1.498e+03,
        1.499e+03,  1.501e+03,  1.502e+03,  1.503e+03,  1.504e+03,
        1.505e+03,  1.506e+03,  1.507e+03,  1.508e+03,  1.509e+03,
        1.511e+03,  1.512e+03,  1.513e+03,  1.514e+03,  1.515e+03,
        1.516e+03,  1.517e+03,  1.518e+03,  1.519e+03,  1.521e+03,
        1.522e+03,  1.523e+03,  1.524e+03,  1.525e+03,  1.526e+03,
        1.527e+03,  1.528e+03,  1.529e+03,  1.531e+03,  1.532e+03,
        1.533e+03,  1.534e+03,  1.535e+03,  1.536e+03,  1.537e+03,
        1.538e+03,  1.539e+03,  1.541e+03,  1.542e+03,  1.543e+03,
        1.544e+03,  1.545e+03,  1.546e+03,  1.547e+03,  1.548e+03,
        1.549e+03,  1.551e+03,  1.552e+03,  1.553e+03,  1.554e+03,
        1.555e+03,  1.556e+03,  1.557e+03,  1.558e+03,  1.559e+03,
        1.561e+03,  1.562e+03,  1.563e+03,  1.564e+03,  1.565e+03,
        1.566e+03,  1.567e+03,  1.568e+03,  1.569e+03,  1.571e+03,
        1.572e+03,  1.573e+03,  1.574e+03,  1.575e+03,  1.576e+03,
        1.577e+03,  1.578e+03,  1.579e+03,  1.581e+03,  1.582e+03,
        1.583e+03,  1.584e+03,  1.585e+03,  1.586e+03,  1.587e+03,
        1.588e+03,  1.589e+03,  1.591e+03,  1.592e+03,  1.593e+03,
        1.594e+03,  1.595e+03,  1.596e+03,  1.597e+03,  1.598e+03,
        1.599e+03,  1.601e+03,  1.602e+03,  1.603e+03,  1.604e+03,
        1.605e+03,  1.606e+03,  1.607e+03,  1.608e+03,  1.609e+03,
        1.611e+03,  1.612e+03,  1.613e+03,  1.614e+03,  1.615e+03,
        1.616e+03,  1.617e+03,  1.618e+03,  1.619e+03,  1.621e+03,
        1.622e+03,  1.623e+03,  1.624e+03,  1.625e+03,  1.626e+03,
        1.627e+03,  1.628e+03,  1.629e+03,  1.630e+03,  1.631e+03,
        1.632e+03,  1.633e+03,  1.634e+03,  1.635e+03,  1.636e+03,
        1.637e+03,  1.638e+03,  1.639e+03,  1.640e+03,  1.641e+03,
        1.642e+03,  1.643e+03,  1.644e+03,  1.645e+03,  1.646e+03,
        1.647e+03,  1.648e+03,  1.649e+03,  1.651e+03,  1.652e+03,
        1.653e+03,  1.654e+03,  1.655e+03,  1.656e+03,  1.657e+03,
        1.658e+03,  1.659e+03,  1.660e+03,  1.662e+03,  1.663e+03,
        1.664e+03,  1.665e+03,  1.666e+03,  1.667e+03,  1.668e+03,
        1.669e+03,  1.670e+03,  1.671e+03,  1.672e+03,  1.673e+03,
        1.674e+03,  1.675e+03,  1.676e+03,  1.677e+03,  1.678e+03,
        1.679e+03,  1.680e+03,  1.681e+03,  1.682e+03,  1.683e+03,
        1.684e+03,  1.686e+03,  1.687e+03,  1.688e+03,  1.689e+03,
        1.691e+03,  1.692e+03,  1.693e+03,  1.694e+03,  1.695e+03,
        1.696e+03,  1.697e+03,  1.698e+03,  1.699e+03,  1.701e+03,
        1.702e+03,  1.703e+03,  1.704e+03,  1.706e+03,  1.707e+03,
        1.708e+03,  1.709e+03,  1.711e+03,  1.712e+03,  1.713e+03,
        1.714e+03,  1.715e+03,  1.716e+03,  1.717e+03,  1.718e+03,
        1.719e+03,  1.721e+03,  1.722e+03,  1.723e+03,  1.725e+03,
        1.726e+03,  1.727e+03,  1.728e+03,  1.729e+03,  1.731e+03,
        1.732e+03,  1.733e+03,  1.734e+03,  1.735e+03,  1.736e+03,
        1.737e+03,  1.738e+03,  1.739e+03,  1.741e+03,  1.742e+03,
        1.743e+03,  1.744e+03,  1.745e+03,  1.746e+03,  1.747e+03,
        1.748e+03,  1.749e+03,  1.751e+03,  1.752e+03,  1.753e+03,
        1.754e+03,  1.756e+03,  1.757e+03,  1.758e+03,  1.759e+03,
        1.761e+03,  1.762e+03,  1.763e+03,  1.764e+03,  1.767e+03,
        1.768e+03,  1.769e+03,  1.771e+03,  1.772e+03,  1.773e+03,
        1.774e+03,  1.776e+03,  1.777e+03,  1.778e+03,  1.779e+03,
        1.781e+03,  1.782e+03,  1.783e+03,  1.784e+03,  1.786e+03,
        1.787e+03,  1.788e+03,  1.789e+03,  1.791e+03,  1.793e+03,
        1.794e+03,  1.796e+03,  1.797e+03,  1.798e+03,  1.799e+03,
        1.252e+03,  1.253e+03,  1.254e+03,  1.255e+03,  1.256e+03,
        1.257e+03,  1.258e+03,  1.259e+03,  1.260e+03,  1.261e+03,
        1.262e+03,  1.263e+03,  1.264e+03,  1.265e+03,  1.266e+03,
        1.267e+03,  1.268e+03,  1.269e+03,  1.271e+03,  1.272e+03,
        1.273e+03,  1.274e+03,  1.275e+03,  1.276e+03,  1.277e+03,
        1.278e+03,  1.279e+03])

In [35]:
Life_Exp.drop(['Code_x'],inplace=True,axis=1)

In [36]:
Life_Exp.duplicated().sum()

0

In [37]:
 Life_Exp.rename(columns = {'Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)'            :'Death by Outdoor air pollution'
,'Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)'            :'Death by high BP'
,'Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)'                     :'Death by high Sodium diet'
,'Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)'                :'Death by low whole grains diet'
,'Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)'                             :'Death by Alcohol use'
,'Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)'                      :'Death by diet low in fruits'
,'Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)'                     :'Death by unsafe water use'
,'Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)'                        :'Death by Passive Smoking'
,'Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)'                        :'Death by Underweight after birth'
,'Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)'                           :'Death by Child wasting'
,'Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)'                              :'Death by Unsafe sex'
,'Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)'              :'Death by Diet low in nuts and seeds'
,'Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)':'Death by Household air pollution'
,'Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)'                  :'Death by Diet low in vegetables'
,'Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)'                   :'Death by Low physical activity'
,'Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)'                                 :'Death by Smoking'
,'Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)'             :'Death by High fasting plasma glucose'
,'Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)'                           :'Death by Air Pollution'
,'Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)'                    :'Death by High BMI'
,'Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)'                       :'Death by Unsafe sanitation'
,'Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)'       :'Death by Sanitation'
,'Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)'                                :'Death by Drug Use'
,'Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)'                :'Death by Low bone mineral density'
,'Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)'                    :'Death by Vitamin A deficiency'
,'Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)'                          :'Death by Child stunting'
,'Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)'              :'Death by Discontinued breastfeeding'
,'Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)'             :'Death by Non-exclusive breastfeeding'
,'Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)'                         :'Death by Iron deficiency'}, inplace = True)

In [38]:
Life_Exp=Life_Exp.fillna(0)

Life_Exp['Death_by_pollution']=Life_Exp['Death by Outdoor air pollution']+Life_Exp['Death by Air Pollution']+Life_Exp['Death by Household air pollution']+Life_Exp['Death by unsafe water use']

Life_Exp['Death_by_malnutrition']=Life_Exp['Death by high Sodium diet']+Life_Exp['Death by low whole grains diet']+Life_Exp['Death by diet low in fruits']+Life_Exp['Death by Underweight after birth']+Life_Exp['Death by Diet low in nuts and seeds']+Life_Exp['Death by Diet low in vegetables']+Life_Exp['Death by High fasting plasma glucose']+Life_Exp['Death by High BMI']+Life_Exp['Death by Low bone mineral density']+Life_Exp['Death by Vitamin A deficiency']+Life_Exp['Death by Discontinued breastfeeding']+Life_Exp['Death by Non-exclusive breastfeeding']+Life_Exp['Death by Iron deficiency']
Life_Exp['Death_by_Alcohol_Abuse']=Life_Exp['Death by Alcohol use']+Life_Exp['Death by Passive Smoking']+Life_Exp['Death by Child wasting']+Life_Exp['Death by Smoking']+Life_Exp['Death by Child stunting']
Life_Exp['Death_by_Other_RF']=Life_Exp['Death by high BP']+Life_Exp['Death by Unsafe sex']+Life_Exp['Death by Unsafe sanitation']+Life_Exp['Death by Sanitation']
Life_Exp.nunique()

Entity                                    455
Code                                      206
Year                                      797
Death by Outdoor air pollution           5768
Death by high BP                         6951
Death by high Sodium diet                4992
Death by low whole grains diet           5472
Death by Alcohol use                     5641
Death by diet low in fruits              4680
Death by unsafe water use                4092
Death by Passive Smoking                 4990
Death by Underweight after birth         5214
Death by Child wasting                   4689
Death by Unsafe sex                      4735
Death by Diet low in nuts and seeds      4043
Death by Household air pollution         4958
Death by Diet low in vegetables          4354
Death by Low physical activity           4498
Death by Smoking                         6521
Death by High fasting plasma glucose     6619
Death by Air Pollution                   6516
Death by High BMI                        6417
Death by Unsafe sanitation               3860
Death by Sanitation                      4046
Death by Drug Use                        3667
Death by Low bone mineral density        3766
Death by Vitamin A deficiency            2151
Death by Child stunting                  3314
Death by Discontinued breastfeeding      1578
Death by Non-exclusive breastfeeding     3314
Death by Iron deficiency                 2030
Daily Calorie Intake                     2736
Population                              51143
Health expenditure per capita            4619
World Happiness Index                     154
$1.90_PER_DAY_BPL                        6084
Life expectancy                         15301
GDP per capita                          11344
$3.20_PER_DAY_BPL                        6405
Death_by_pollution                       7004
Death_by_malnutrition                    7409
Death_by_Alcohol_Abuse                   7097
Death_by_Other_RF                        7177
dtype: int64

In [39]:
Life_Exp.drop(['Death by Outdoor air pollution',   
'Death by high BP',          
'Death by high Sodium diet',              
'Death by low whole grains diet',           
'Death by Alcohol use',                    
'Death by diet low in fruits',              
'Death by unsafe water use',                 
'Death by Passive Smoking',                  
'Death by Underweight after birth',         
'Death by Child wasting',                
'Death by Unsafe sex',                      
'Death by Diet low in nuts and seeds',      
'Death by Household air pollution',          
'Death by Diet low in vegetables',          
'Death by Low physical activity',           
'Death by Smoking',                         
'Death by High fasting plasma glucose',     
'Death by Air Pollution',                    
'Death by High BMI',                       
'Death by Unsafe sanitation',               
'Death by Sanitation',                     
'Death by Drug Use',                        
'Death by Low bone mineral density',        
'Death by Vitamin A deficiency',             
'Death by Child stunting',                  
'Death by Discontinued breastfeeding',       
'Death by Non-exclusive breastfeeding',     
'Death by Iron deficiency'],inplace=True,axis=1)

In [40]:
Life_Exp.nunique()

Entity                             455
Code                               206
Year                               797
Daily Calorie Intake              2736
Population                       51143
Health expenditure per capita     4619
World Happiness Index              154
$1.90_PER_DAY_BPL                 6084
Life expectancy                  15301
GDP per capita                   11344
$3.20_PER_DAY_BPL                 6405
Death_by_pollution                7004
Death_by_malnutrition             7409
Death_by_Alcohol_Abuse            7097
Death_by_Other_RF                 7177
dtype: int64

In [41]:
data8= pd.read_csv('annual-number-of-deaths-by-cause.csv')
Life_Exp= pd.merge(data8, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

(67814, 49)

In [42]:
Life_Exp.nunique()

Entity                                                                                        467
Code_x                                                                                        217
Year                                                                                          797
Number of executions (Amnesty International)                                                   81
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                     3652
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                      6823
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)                 3101
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                        2820
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                       3618
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                         3933
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                       4156
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                             2407
Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                   4618
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                                  5263
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                             3274
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                   6096
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                             5399
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                          2999
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                   1553
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                             4615
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)           2199
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                       3791
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                      4634
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                         2179
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                              5298
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                     2644
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                    3683
Terrorism (deaths)                                                                            554
Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                        7246
Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                         5133
Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                   5792
Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)     5344
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                             5993
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                                2351
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)        4957
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                            3627
Code_y                                                                                        206
Daily Calorie Intake                                                                         2736
Population                                                                                  51143
Health expenditure per capita                                                                4619
World Happiness Index                                                                         154
$1.90_PER_DAY_BPL                                                                            6084
Life expectancy                                                                             15301
GDP per capita                                                                              11344
$3.20_PER_DAY_BPL                                                                            6405
Death_by_pollution                                                                           7004
Death_by_malnutrition                                                                        7409
Death_by_Alcohol_Abuse                                                                       7097
Death_by_Other_RF                                                                            7177
dtype: int64

In [43]:
Life_Exp.rename(columns = {'Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)'                     :'Death by Cirrhosis'
,'Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)'                :'Death by Respiratory disease'
,'Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)'                             :'Death by Kidney disease'
,'Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)'                      :'Death by Cardiovascular disease'
,'Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)'                     :'Death by HIV/AIDS'
,'Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)'                        :'Death by Tuberculosis'}, inplace = True)

In [44]:
Life_Exp.nunique()

Entity                                                                                     467
Code_x                                                                                     217
Year                                                                                       797
Number of executions (Amnesty International)                                                81
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  3652
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                   6823
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)              3101
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     2820
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    3618
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      3933
Death by HIV/AIDS                                                                         4156
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                          2407
Death by Tuberculosis                                                                     4618
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                               5263
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                          3274
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                6096
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                          5399
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                       2999
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                1553
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                          4615
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)        2199
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    3791
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   4634
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      2179
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                           5298
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  2644
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 3683
Terrorism (deaths)                                                                         554
Death by Cardiovascular disease                                                           7246
Death by Kidney disease                                                                   5133
Death by Respiratory disease                                                              5792
Death by Cirrhosis                                                                        5344
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                          5993
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                             2351
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     4957
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         3627
Code_y                                                                                     206
Daily Calorie Intake                                                                      2736
Population                                                                               51143
Health expenditure per capita                                                             4619
World Happiness Index                                                                      154
$1.90_PER_DAY_BPL                                                                         6084
Life expectancy                                                                          15301
GDP per capita                                                                           11344
$3.20_PER_DAY_BPL                                                                         6405
Death_by_pollution                                                                        7004
Death_by_malnutrition                                                                     7409
Death_by_Alcohol_Abuse                                                                    7097
Death_by_Other_RF                                                                         7177
dtype: int64

In [45]:
Life_Exp.Year.unique()

array([ 2.007e+03,  2.008e+03,  2.009e+03,  2.011e+03,  2.012e+03,
        2.013e+03,  2.014e+03,  2.015e+03,  2.016e+03,  1.990e+03,
        1.991e+03,  1.992e+03,  1.993e+03,  1.994e+03,  1.995e+03,
        1.996e+03,  1.997e+03,  1.998e+03,  1.999e+03,  2.000e+03,
        2.001e+03,  2.002e+03,  2.003e+03,  2.004e+03,  2.005e+03,
        2.006e+03,  2.010e+03,  2.017e+03,  2.018e+03,  2.019e+03,
        1.950e+03,  1.951e+03,  1.952e+03,  1.953e+03,  1.954e+03,
        1.955e+03,  1.956e+03,  1.957e+03,  1.958e+03,  1.959e+03,
        1.960e+03,  1.961e+03,  1.962e+03,  1.963e+03,  1.964e+03,
        1.965e+03,  1.966e+03,  1.967e+03,  1.968e+03,  1.969e+03,
        1.970e+03,  1.971e+03,  1.972e+03,  1.973e+03,  1.974e+03,
        1.975e+03,  1.976e+03,  1.977e+03,  1.978e+03,  1.979e+03,
        1.980e+03,  1.981e+03,  1.982e+03,  1.983e+03,  1.984e+03,
        1.985e+03,  1.986e+03,  1.987e+03,  1.988e+03,  1.989e+03,
        2.020e+03, -1.000e+04, -9.000e+03, -8.000e+03, -7.000e+03,
       -6.000e+03, -5.000e+03, -4.000e+03, -3.000e+03, -2.000e+03,
       -1.000e+03,  0.000e+00,  1.000e+02,  2.000e+02,  3.000e+02,
        4.000e+02,  5.000e+02,  6.000e+02,  7.000e+02,  8.000e+02,
        9.000e+02,  1.000e+03,  1.100e+03,  1.200e+03,  1.300e+03,
        1.400e+03,  1.500e+03,  1.600e+03,  1.700e+03,  1.710e+03,
        1.720e+03,  1.730e+03,  1.740e+03,  1.750e+03,  1.760e+03,
        1.770e+03,  1.780e+03,  1.790e+03,  1.800e+03,  1.801e+03,
        1.802e+03,  1.803e+03,  1.804e+03,  1.805e+03,  1.806e+03,
        1.807e+03,  1.808e+03,  1.809e+03,  1.810e+03,  1.811e+03,
        1.812e+03,  1.813e+03,  1.814e+03,  1.815e+03,  1.816e+03,
        1.817e+03,  1.818e+03,  1.819e+03,  1.820e+03,  1.821e+03,
        1.822e+03,  1.823e+03,  1.824e+03,  1.825e+03,  1.826e+03,
        1.827e+03,  1.828e+03,  1.829e+03,  1.830e+03,  1.831e+03,
        1.832e+03,  1.833e+03,  1.834e+03,  1.835e+03,  1.836e+03,
        1.837e+03,  1.838e+03,  1.839e+03,  1.840e+03,  1.841e+03,
        1.842e+03,  1.843e+03,  1.844e+03,  1.845e+03,  1.846e+03,
        1.847e+03,  1.848e+03,  1.849e+03,  1.850e+03,  1.851e+03,
        1.852e+03,  1.853e+03,  1.854e+03,  1.855e+03,  1.856e+03,
        1.857e+03,  1.858e+03,  1.859e+03,  1.860e+03,  1.861e+03,
        1.862e+03,  1.863e+03,  1.864e+03,  1.865e+03,  1.866e+03,
        1.867e+03,  1.868e+03,  1.869e+03,  1.870e+03,  1.871e+03,
        1.872e+03,  1.873e+03,  1.874e+03,  1.875e+03,  1.876e+03,
        1.877e+03,  1.878e+03,  1.879e+03,  1.880e+03,  1.881e+03,
        1.882e+03,  1.883e+03,  1.884e+03,  1.885e+03,  1.886e+03,
        1.887e+03,  1.888e+03,  1.889e+03,  1.890e+03,  1.891e+03,
        1.892e+03,  1.893e+03,  1.894e+03,  1.895e+03,  1.896e+03,
        1.897e+03,  1.898e+03,  1.899e+03,  1.900e+03,  1.901e+03,
        1.902e+03,  1.903e+03,  1.904e+03,  1.905e+03,  1.906e+03,
        1.907e+03,  1.908e+03,  1.909e+03,  1.910e+03,  1.911e+03,
        1.912e+03,  1.913e+03,  1.914e+03,  1.915e+03,  1.916e+03,
        1.917e+03,  1.918e+03,  1.919e+03,  1.920e+03,  1.921e+03,
        1.922e+03,  1.923e+03,  1.924e+03,  1.925e+03,  1.926e+03,
        1.927e+03,  1.928e+03,  1.929e+03,  1.930e+03,  1.931e+03,
        1.932e+03,  1.933e+03,  1.934e+03,  1.935e+03,  1.936e+03,
        1.937e+03,  1.938e+03,  1.939e+03,  1.940e+03,  1.941e+03,
        1.942e+03,  1.943e+03,  1.944e+03,  1.945e+03,  1.946e+03,
        1.947e+03,  1.948e+03,  1.949e+03,  2.021e+03,  1.705e+03,
        1.270e+03,  1.310e+03,  1.380e+03,  1.420e+03,  1.450e+03,
        1.000e+00,  1.550e+03,  1.650e+03,  1.090e+03,  1.120e+03,
        1.410e+03,  1.430e+03,  1.440e+03,  1.460e+03,  1.470e+03,
        1.480e+03,  1.490e+03,  1.510e+03,  1.520e+03,  1.530e+03,
        1.540e+03,  1.560e+03,  1.570e+03,  1.580e+03,  1.590e+03,
        1.610e+03,  1.620e+03,  1.661e+03,  1.685e+03,  1.690e+03,
        1.724e+03,  1.766e+03,  1.775e+03,  1.792e+03,  7.300e+02,
        1.280e+03,  1.755e+03,  1.765e+03,  1.785e+03,  1.795e+03,
        1.281e+03,  1.282e+03,  1.283e+03,  1.284e+03,  1.285e+03,
        1.286e+03,  1.287e+03,  1.288e+03,  1.289e+03,  1.290e+03,
        1.291e+03,  1.292e+03,  1.293e+03,  1.294e+03,  1.295e+03,
        1.296e+03,  1.297e+03,  1.298e+03,  1.299e+03,  1.301e+03,
        1.302e+03,  1.303e+03,  1.304e+03,  1.305e+03,  1.306e+03,
        1.307e+03,  1.308e+03,  1.309e+03,  1.311e+03,  1.312e+03,
        1.313e+03,  1.314e+03,  1.315e+03,  1.316e+03,  1.317e+03,
        1.318e+03,  1.319e+03,  1.320e+03,  1.321e+03,  1.322e+03,
        1.323e+03,  1.324e+03,  1.325e+03,  1.326e+03,  1.327e+03,
        1.328e+03,  1.329e+03,  1.330e+03,  1.331e+03,  1.332e+03,
        1.333e+03,  1.334e+03,  1.335e+03,  1.336e+03,  1.337e+03,
        1.338e+03,  1.339e+03,  1.340e+03,  1.341e+03,  1.342e+03,
        1.343e+03,  1.344e+03,  1.345e+03,  1.346e+03,  1.347e+03,
        1.348e+03,  1.349e+03,  1.350e+03,  1.351e+03,  1.352e+03,
        1.353e+03,  1.354e+03,  1.355e+03,  1.356e+03,  1.357e+03,
        1.358e+03,  1.359e+03,  1.360e+03,  1.361e+03,  1.362e+03,
        1.363e+03,  1.364e+03,  1.365e+03,  1.366e+03,  1.367e+03,
        1.368e+03,  1.369e+03,  1.370e+03,  1.371e+03,  1.372e+03,
        1.373e+03,  1.374e+03,  1.375e+03,  1.376e+03,  1.377e+03,
        1.378e+03,  1.379e+03,  1.381e+03,  1.382e+03,  1.383e+03,
        1.384e+03,  1.385e+03,  1.386e+03,  1.387e+03,  1.388e+03,
        1.389e+03,  1.390e+03,  1.391e+03,  1.392e+03,  1.393e+03,
        1.394e+03,  1.395e+03,  1.396e+03,  1.397e+03,  1.398e+03,
        1.399e+03,  1.401e+03,  1.402e+03,  1.403e+03,  1.404e+03,
        1.405e+03,  1.406e+03,  1.407e+03,  1.408e+03,  1.409e+03,
        1.411e+03,  1.412e+03,  1.413e+03,  1.414e+03,  1.415e+03,
        1.416e+03,  1.417e+03,  1.418e+03,  1.419e+03,  1.421e+03,
        1.422e+03,  1.423e+03,  1.424e+03,  1.425e+03,  1.426e+03,
        1.427e+03,  1.428e+03,  1.429e+03,  1.431e+03,  1.432e+03,
        1.433e+03,  1.434e+03,  1.435e+03,  1.436e+03,  1.437e+03,
        1.438e+03,  1.439e+03,  1.441e+03,  1.442e+03,  1.443e+03,
        1.444e+03,  1.445e+03,  1.446e+03,  1.447e+03,  1.448e+03,
        1.449e+03,  1.451e+03,  1.452e+03,  1.453e+03,  1.454e+03,
        1.455e+03,  1.456e+03,  1.457e+03,  1.458e+03,  1.459e+03,
        1.461e+03,  1.462e+03,  1.463e+03,  1.464e+03,  1.465e+03,
        1.466e+03,  1.467e+03,  1.468e+03,  1.469e+03,  1.471e+03,
        1.472e+03,  1.473e+03,  1.474e+03,  1.475e+03,  1.476e+03,
        1.477e+03,  1.478e+03,  1.479e+03,  1.481e+03,  1.482e+03,
        1.483e+03,  1.484e+03,  1.485e+03,  1.486e+03,  1.487e+03,
        1.488e+03,  1.489e+03,  1.491e+03,  1.492e+03,  1.493e+03,
        1.494e+03,  1.495e+03,  1.496e+03,  1.497e+03,  1.498e+03,
        1.499e+03,  1.501e+03,  1.502e+03,  1.503e+03,  1.504e+03,
        1.505e+03,  1.506e+03,  1.507e+03,  1.508e+03,  1.509e+03,
        1.511e+03,  1.512e+03,  1.513e+03,  1.514e+03,  1.515e+03,
        1.516e+03,  1.517e+03,  1.518e+03,  1.519e+03,  1.521e+03,
        1.522e+03,  1.523e+03,  1.524e+03,  1.525e+03,  1.526e+03,
        1.527e+03,  1.528e+03,  1.529e+03,  1.531e+03,  1.532e+03,
        1.533e+03,  1.534e+03,  1.535e+03,  1.536e+03,  1.537e+03,
        1.538e+03,  1.539e+03,  1.541e+03,  1.542e+03,  1.543e+03,
        1.544e+03,  1.545e+03,  1.546e+03,  1.547e+03,  1.548e+03,
        1.549e+03,  1.551e+03,  1.552e+03,  1.553e+03,  1.554e+03,
        1.555e+03,  1.556e+03,  1.557e+03,  1.558e+03,  1.559e+03,
        1.561e+03,  1.562e+03,  1.563e+03,  1.564e+03,  1.565e+03,
        1.566e+03,  1.567e+03,  1.568e+03,  1.569e+03,  1.571e+03,
        1.572e+03,  1.573e+03,  1.574e+03,  1.575e+03,  1.576e+03,
        1.577e+03,  1.578e+03,  1.579e+03,  1.581e+03,  1.582e+03,
        1.583e+03,  1.584e+03,  1.585e+03,  1.586e+03,  1.587e+03,
        1.588e+03,  1.589e+03,  1.591e+03,  1.592e+03,  1.593e+03,
        1.594e+03,  1.595e+03,  1.596e+03,  1.597e+03,  1.598e+03,
        1.599e+03,  1.601e+03,  1.602e+03,  1.603e+03,  1.604e+03,
        1.605e+03,  1.606e+03,  1.607e+03,  1.608e+03,  1.609e+03,
        1.611e+03,  1.612e+03,  1.613e+03,  1.614e+03,  1.615e+03,
        1.616e+03,  1.617e+03,  1.618e+03,  1.619e+03,  1.621e+03,
        1.622e+03,  1.623e+03,  1.624e+03,  1.625e+03,  1.626e+03,
        1.627e+03,  1.628e+03,  1.629e+03,  1.630e+03,  1.631e+03,
        1.632e+03,  1.633e+03,  1.634e+03,  1.635e+03,  1.636e+03,
        1.637e+03,  1.638e+03,  1.639e+03,  1.640e+03,  1.641e+03,
        1.642e+03,  1.643e+03,  1.644e+03,  1.645e+03,  1.646e+03,
        1.647e+03,  1.648e+03,  1.649e+03,  1.651e+03,  1.652e+03,
        1.653e+03,  1.654e+03,  1.655e+03,  1.656e+03,  1.657e+03,
        1.658e+03,  1.659e+03,  1.660e+03,  1.662e+03,  1.663e+03,
        1.664e+03,  1.665e+03,  1.666e+03,  1.667e+03,  1.668e+03,
        1.669e+03,  1.670e+03,  1.671e+03,  1.672e+03,  1.673e+03,
        1.674e+03,  1.675e+03,  1.676e+03,  1.677e+03,  1.678e+03,
        1.679e+03,  1.680e+03,  1.681e+03,  1.682e+03,  1.683e+03,
        1.684e+03,  1.686e+03,  1.687e+03,  1.688e+03,  1.689e+03,
        1.691e+03,  1.692e+03,  1.693e+03,  1.694e+03,  1.695e+03,
        1.696e+03,  1.697e+03,  1.698e+03,  1.699e+03,  1.701e+03,
        1.702e+03,  1.703e+03,  1.704e+03,  1.706e+03,  1.707e+03,
        1.708e+03,  1.709e+03,  1.711e+03,  1.712e+03,  1.713e+03,
        1.714e+03,  1.715e+03,  1.716e+03,  1.717e+03,  1.718e+03,
        1.719e+03,  1.721e+03,  1.722e+03,  1.723e+03,  1.725e+03,
        1.726e+03,  1.727e+03,  1.728e+03,  1.729e+03,  1.731e+03,
        1.732e+03,  1.733e+03,  1.734e+03,  1.735e+03,  1.736e+03,
        1.737e+03,  1.738e+03,  1.739e+03,  1.741e+03,  1.742e+03,
        1.743e+03,  1.744e+03,  1.745e+03,  1.746e+03,  1.747e+03,
        1.748e+03,  1.749e+03,  1.751e+03,  1.752e+03,  1.753e+03,
        1.754e+03,  1.756e+03,  1.757e+03,  1.758e+03,  1.759e+03,
        1.761e+03,  1.762e+03,  1.763e+03,  1.764e+03,  1.767e+03,
        1.768e+03,  1.769e+03,  1.771e+03,  1.772e+03,  1.773e+03,
        1.774e+03,  1.776e+03,  1.777e+03,  1.778e+03,  1.779e+03,
        1.781e+03,  1.782e+03,  1.783e+03,  1.784e+03,  1.786e+03,
        1.787e+03,  1.788e+03,  1.789e+03,  1.791e+03,  1.793e+03,
        1.794e+03,  1.796e+03,  1.797e+03,  1.798e+03,  1.799e+03,
        1.252e+03,  1.253e+03,  1.254e+03,  1.255e+03,  1.256e+03,
        1.257e+03,  1.258e+03,  1.259e+03,  1.260e+03,  1.261e+03,
        1.262e+03,  1.263e+03,  1.264e+03,  1.265e+03,  1.266e+03,
        1.267e+03,  1.268e+03,  1.269e+03,  1.271e+03,  1.272e+03,
        1.273e+03,  1.274e+03,  1.275e+03,  1.276e+03,  1.277e+03,
        1.278e+03,  1.279e+03])

In [46]:
Life_Exp['Death_by_Alcohol_&_Drugs']=Life_Exp['Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)']

In [47]:
Life_Exp=Life_Exp.fillna(0)

Life_Exp['Death_by_other_disease']=Life_Exp['Deaths - Road injuries - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)']+Life_Exp['Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)']
Life_Exp.nunique()

Entity                                                                                     467
Code_x                                                                                     218
Year                                                                                       797
Number of executions (Amnesty International)                                                82
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  3652
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                   6824
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)              3101
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     2820
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    3618
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      3933
Death by HIV/AIDS                                                                         4156
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                          2407
Death by Tuberculosis                                                                     4618
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                               5263
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                          3274
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                6096
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                          5399
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                       2999
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                1553
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                          4615
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)        2199
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    3791
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   4634
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      2179
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                           5299
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  2644
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 3683
Terrorism (deaths)                                                                         554
Death by Cardiovascular disease                                                           7247
Death by Kidney disease                                                                   5133
Death by Respiratory disease                                                              5793
Death by Cirrhosis                                                                        5344
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                          5993
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                             2351
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     4957
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         3627
Code_y                                                                                     206
Daily Calorie Intake                                                                      2736
Population                                                                               51143
Health expenditure per capita                                                             4619
World Happiness Index                                                                      154
$1.90_PER_DAY_BPL                                                                         6084
Life expectancy                                                                          15301
GDP per capita                                                                           11344
$3.20_PER_DAY_BPL                                                                         6405
Death_by_pollution                                                                        7004
Death_by_malnutrition                                                                     7409
Death_by_Alcohol_Abuse                                                                    7097
Death_by_Other_RF                                                                         7177
Death_by_Alcohol_&_Drugs                                                                  3321
Death_by_other_disease                                                                    7457
dtype: int64

In [48]:
Life_Exp.drop(['Deaths - Road injuries - Sex: Both - Age: All Ages (Number)','Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)','Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)',
'Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)','Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)','Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)',
'Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)','Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)','Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)',
'Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)','Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)','Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)',
              'Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)','Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)'],inplace=True,axis=1)

In [49]:
Life_Exp.nunique()

Entity                                                                                     467
Code_x                                                                                     218
Year                                                                                       797
Number of executions (Amnesty International)                                                82
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  3652
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     2820
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    3618
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      3933
Death by HIV/AIDS                                                                         4156
Death by Tuberculosis                                                                     4618
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    3791
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   4634
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      2179
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  2644
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 3683
Terrorism (deaths)                                                                         554
Death by Cardiovascular disease                                                           7247
Death by Kidney disease                                                                   5133
Death by Respiratory disease                                                              5793
Death by Cirrhosis                                                                        5344
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     4957
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         3627
Code_y                                                                                     206
Daily Calorie Intake                                                                      2736
Population                                                                               51143
Health expenditure per capita                                                             4619
World Happiness Index                                                                      154
$1.90_PER_DAY_BPL                                                                         6084
Life expectancy                                                                          15301
GDP per capita                                                                           11344
$3.20_PER_DAY_BPL                                                                         6405
Death_by_pollution                                                                        7004
Death_by_malnutrition                                                                     7409
Death_by_Alcohol_Abuse                                                                    7097
Death_by_Other_RF                                                                         7177
Death_by_Alcohol_&_Drugs                                                                  3321
Death_by_other_disease                                                                    7457
dtype: int64

In [50]:
Life_Exp.duplicated().sum()

0

In [51]:
data9= pd.read_csv('causes-of-death-in-children-under-5.csv')
data9['infant_death']=data9['Deaths - Invasive Non-typhoidal Salmonella (iNTS) - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Interpersonal violence - Sex: Both - Age: Under 5 (Number)']+ data9['Deaths - Nutritional deficiencies - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Acute hepatitis - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Neoplasms - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Measles - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Digestive diseases - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Chronic kidney disease - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Cardiovascular diseases - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Congenital birth defects - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Lower respiratory infections - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Neonatal preterm birth - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Environmental heat and cold exposure - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Neonatal sepsis and other neonatal infections - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Exposure to forces of nature - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Diabetes mellitus - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Neonatal encephalopathy due to birth asphyxia and trauma - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Meningitis - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Other neonatal disorders - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Whooping cough - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Diarrheal diseases - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Fire, heat, and hot substances - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Road injuries - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Tuberculosis - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - HIV/AIDS - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Drowning - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Malaria - Sex: Both - Age: Under 5 (Number)']+data9['Deaths - Syphilis - Sex: Both - Age: Under 5 (Number)']
data10=pd.DataFrame(data9[['Entity','Year','infant_death']])

In [52]:
Life_Exp= pd.merge(data10, Life_Exp,on=['Entity','Year'],how='outer')
np.shape(Life_Exp)

(67814, 38)

In [53]:
Life_Exp.nunique()

Entity                                                                                     467
Year                                                                                       797
infant_death                                                                              6071
Code_x                                                                                     218
Number of executions (Amnesty International)                                                82
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  3652
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     2820
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    3618
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      3933
Death by HIV/AIDS                                                                         4156
Death by Tuberculosis                                                                     4618
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    3791
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   4634
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      2179
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  2644
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 3683
Terrorism (deaths)                                                                         554
Death by Cardiovascular disease                                                           7247
Death by Kidney disease                                                                   5133
Death by Respiratory disease                                                              5793
Death by Cirrhosis                                                                        5344
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     4957
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         3627
Code_y                                                                                     206
Daily Calorie Intake                                                                      2736
Population                                                                               51143
Health expenditure per capita                                                             4619
World Happiness Index                                                                      154
$1.90_PER_DAY_BPL                                                                         6084
Life expectancy                                                                          15301
GDP per capita                                                                           11344
$3.20_PER_DAY_BPL                                                                         6405
Death_by_pollution                                                                        7004
Death_by_malnutrition                                                                     7409
Death_by_Alcohol_Abuse                                                                    7097
Death_by_Other_RF                                                                         7177
Death_by_Alcohol_&_Drugs                                                                  3321
Death_by_other_disease                                                                    7457
dtype: int64

In [54]:
Life_Exp.Year.unique()

array([ 1.990e+03,  1.991e+03,  1.992e+03,  1.993e+03,  1.994e+03,
        1.995e+03,  1.996e+03,  1.997e+03,  1.998e+03,  1.999e+03,
        2.000e+03,  2.001e+03,  2.002e+03,  2.003e+03,  2.004e+03,
        2.005e+03,  2.006e+03,  2.007e+03,  2.008e+03,  2.009e+03,
        2.010e+03,  2.011e+03,  2.012e+03,  2.013e+03,  2.014e+03,
        2.015e+03,  2.016e+03,  2.017e+03,  2.018e+03,  2.019e+03,
        1.950e+03,  1.951e+03,  1.952e+03,  1.953e+03,  1.954e+03,
        1.955e+03,  1.956e+03,  1.957e+03,  1.958e+03,  1.959e+03,
        1.960e+03,  1.961e+03,  1.962e+03,  1.963e+03,  1.964e+03,
        1.965e+03,  1.966e+03,  1.967e+03,  1.968e+03,  1.969e+03,
        1.970e+03,  1.971e+03,  1.972e+03,  1.973e+03,  1.974e+03,
        1.975e+03,  1.976e+03,  1.977e+03,  1.978e+03,  1.979e+03,
        1.980e+03,  1.981e+03,  1.982e+03,  1.983e+03,  1.984e+03,
        1.985e+03,  1.986e+03,  1.987e+03,  1.988e+03,  1.989e+03,
        2.020e+03, -1.000e+04, -9.000e+03, -8.000e+03, -7.000e+03,
       -6.000e+03, -5.000e+03, -4.000e+03, -3.000e+03, -2.000e+03,
       -1.000e+03,  0.000e+00,  1.000e+02,  2.000e+02,  3.000e+02,
        4.000e+02,  5.000e+02,  6.000e+02,  7.000e+02,  8.000e+02,
        9.000e+02,  1.000e+03,  1.100e+03,  1.200e+03,  1.300e+03,
        1.400e+03,  1.500e+03,  1.600e+03,  1.700e+03,  1.710e+03,
        1.720e+03,  1.730e+03,  1.740e+03,  1.750e+03,  1.760e+03,
        1.770e+03,  1.780e+03,  1.790e+03,  1.800e+03,  1.801e+03,
        1.802e+03,  1.803e+03,  1.804e+03,  1.805e+03,  1.806e+03,
        1.807e+03,  1.808e+03,  1.809e+03,  1.810e+03,  1.811e+03,
        1.812e+03,  1.813e+03,  1.814e+03,  1.815e+03,  1.816e+03,
        1.817e+03,  1.818e+03,  1.819e+03,  1.820e+03,  1.821e+03,
        1.822e+03,  1.823e+03,  1.824e+03,  1.825e+03,  1.826e+03,
        1.827e+03,  1.828e+03,  1.829e+03,  1.830e+03,  1.831e+03,
        1.832e+03,  1.833e+03,  1.834e+03,  1.835e+03,  1.836e+03,
        1.837e+03,  1.838e+03,  1.839e+03,  1.840e+03,  1.841e+03,
        1.842e+03,  1.843e+03,  1.844e+03,  1.845e+03,  1.846e+03,
        1.847e+03,  1.848e+03,  1.849e+03,  1.850e+03,  1.851e+03,
        1.852e+03,  1.853e+03,  1.854e+03,  1.855e+03,  1.856e+03,
        1.857e+03,  1.858e+03,  1.859e+03,  1.860e+03,  1.861e+03,
        1.862e+03,  1.863e+03,  1.864e+03,  1.865e+03,  1.866e+03,
        1.867e+03,  1.868e+03,  1.869e+03,  1.870e+03,  1.871e+03,
        1.872e+03,  1.873e+03,  1.874e+03,  1.875e+03,  1.876e+03,
        1.877e+03,  1.878e+03,  1.879e+03,  1.880e+03,  1.881e+03,
        1.882e+03,  1.883e+03,  1.884e+03,  1.885e+03,  1.886e+03,
        1.887e+03,  1.888e+03,  1.889e+03,  1.890e+03,  1.891e+03,
        1.892e+03,  1.893e+03,  1.894e+03,  1.895e+03,  1.896e+03,
        1.897e+03,  1.898e+03,  1.899e+03,  1.900e+03,  1.901e+03,
        1.902e+03,  1.903e+03,  1.904e+03,  1.905e+03,  1.906e+03,
        1.907e+03,  1.908e+03,  1.909e+03,  1.910e+03,  1.911e+03,
        1.912e+03,  1.913e+03,  1.914e+03,  1.915e+03,  1.916e+03,
        1.917e+03,  1.918e+03,  1.919e+03,  1.920e+03,  1.921e+03,
        1.922e+03,  1.923e+03,  1.924e+03,  1.925e+03,  1.926e+03,
        1.927e+03,  1.928e+03,  1.929e+03,  1.930e+03,  1.931e+03,
        1.932e+03,  1.933e+03,  1.934e+03,  1.935e+03,  1.936e+03,
        1.937e+03,  1.938e+03,  1.939e+03,  1.940e+03,  1.941e+03,
        1.942e+03,  1.943e+03,  1.944e+03,  1.945e+03,  1.946e+03,
        1.947e+03,  1.948e+03,  1.949e+03,  2.021e+03,  1.705e+03,
        1.270e+03,  1.310e+03,  1.380e+03,  1.420e+03,  1.450e+03,
        1.000e+00,  1.550e+03,  1.650e+03,  1.090e+03,  1.120e+03,
        1.410e+03,  1.430e+03,  1.440e+03,  1.460e+03,  1.470e+03,
        1.480e+03,  1.490e+03,  1.510e+03,  1.520e+03,  1.530e+03,
        1.540e+03,  1.560e+03,  1.570e+03,  1.580e+03,  1.590e+03,
        1.610e+03,  1.620e+03,  1.661e+03,  1.685e+03,  1.690e+03,
        1.724e+03,  1.766e+03,  1.775e+03,  1.792e+03,  7.300e+02,
        1.280e+03,  1.755e+03,  1.765e+03,  1.785e+03,  1.795e+03,
        1.281e+03,  1.282e+03,  1.283e+03,  1.284e+03,  1.285e+03,
        1.286e+03,  1.287e+03,  1.288e+03,  1.289e+03,  1.290e+03,
        1.291e+03,  1.292e+03,  1.293e+03,  1.294e+03,  1.295e+03,
        1.296e+03,  1.297e+03,  1.298e+03,  1.299e+03,  1.301e+03,
        1.302e+03,  1.303e+03,  1.304e+03,  1.305e+03,  1.306e+03,
        1.307e+03,  1.308e+03,  1.309e+03,  1.311e+03,  1.312e+03,
        1.313e+03,  1.314e+03,  1.315e+03,  1.316e+03,  1.317e+03,
        1.318e+03,  1.319e+03,  1.320e+03,  1.321e+03,  1.322e+03,
        1.323e+03,  1.324e+03,  1.325e+03,  1.326e+03,  1.327e+03,
        1.328e+03,  1.329e+03,  1.330e+03,  1.331e+03,  1.332e+03,
        1.333e+03,  1.334e+03,  1.335e+03,  1.336e+03,  1.337e+03,
        1.338e+03,  1.339e+03,  1.340e+03,  1.341e+03,  1.342e+03,
        1.343e+03,  1.344e+03,  1.345e+03,  1.346e+03,  1.347e+03,
        1.348e+03,  1.349e+03,  1.350e+03,  1.351e+03,  1.352e+03,
        1.353e+03,  1.354e+03,  1.355e+03,  1.356e+03,  1.357e+03,
        1.358e+03,  1.359e+03,  1.360e+03,  1.361e+03,  1.362e+03,
        1.363e+03,  1.364e+03,  1.365e+03,  1.366e+03,  1.367e+03,
        1.368e+03,  1.369e+03,  1.370e+03,  1.371e+03,  1.372e+03,
        1.373e+03,  1.374e+03,  1.375e+03,  1.376e+03,  1.377e+03,
        1.378e+03,  1.379e+03,  1.381e+03,  1.382e+03,  1.383e+03,
        1.384e+03,  1.385e+03,  1.386e+03,  1.387e+03,  1.388e+03,
        1.389e+03,  1.390e+03,  1.391e+03,  1.392e+03,  1.393e+03,
        1.394e+03,  1.395e+03,  1.396e+03,  1.397e+03,  1.398e+03,
        1.399e+03,  1.401e+03,  1.402e+03,  1.403e+03,  1.404e+03,
        1.405e+03,  1.406e+03,  1.407e+03,  1.408e+03,  1.409e+03,
        1.411e+03,  1.412e+03,  1.413e+03,  1.414e+03,  1.415e+03,
        1.416e+03,  1.417e+03,  1.418e+03,  1.419e+03,  1.421e+03,
        1.422e+03,  1.423e+03,  1.424e+03,  1.425e+03,  1.426e+03,
        1.427e+03,  1.428e+03,  1.429e+03,  1.431e+03,  1.432e+03,
        1.433e+03,  1.434e+03,  1.435e+03,  1.436e+03,  1.437e+03,
        1.438e+03,  1.439e+03,  1.441e+03,  1.442e+03,  1.443e+03,
        1.444e+03,  1.445e+03,  1.446e+03,  1.447e+03,  1.448e+03,
        1.449e+03,  1.451e+03,  1.452e+03,  1.453e+03,  1.454e+03,
        1.455e+03,  1.456e+03,  1.457e+03,  1.458e+03,  1.459e+03,
        1.461e+03,  1.462e+03,  1.463e+03,  1.464e+03,  1.465e+03,
        1.466e+03,  1.467e+03,  1.468e+03,  1.469e+03,  1.471e+03,
        1.472e+03,  1.473e+03,  1.474e+03,  1.475e+03,  1.476e+03,
        1.477e+03,  1.478e+03,  1.479e+03,  1.481e+03,  1.482e+03,
        1.483e+03,  1.484e+03,  1.485e+03,  1.486e+03,  1.487e+03,
        1.488e+03,  1.489e+03,  1.491e+03,  1.492e+03,  1.493e+03,
        1.494e+03,  1.495e+03,  1.496e+03,  1.497e+03,  1.498e+03,
        1.499e+03,  1.501e+03,  1.502e+03,  1.503e+03,  1.504e+03,
        1.505e+03,  1.506e+03,  1.507e+03,  1.508e+03,  1.509e+03,
        1.511e+03,  1.512e+03,  1.513e+03,  1.514e+03,  1.515e+03,
        1.516e+03,  1.517e+03,  1.518e+03,  1.519e+03,  1.521e+03,
        1.522e+03,  1.523e+03,  1.524e+03,  1.525e+03,  1.526e+03,
        1.527e+03,  1.528e+03,  1.529e+03,  1.531e+03,  1.532e+03,
        1.533e+03,  1.534e+03,  1.535e+03,  1.536e+03,  1.537e+03,
        1.538e+03,  1.539e+03,  1.541e+03,  1.542e+03,  1.543e+03,
        1.544e+03,  1.545e+03,  1.546e+03,  1.547e+03,  1.548e+03,
        1.549e+03,  1.551e+03,  1.552e+03,  1.553e+03,  1.554e+03,
        1.555e+03,  1.556e+03,  1.557e+03,  1.558e+03,  1.559e+03,
        1.561e+03,  1.562e+03,  1.563e+03,  1.564e+03,  1.565e+03,
        1.566e+03,  1.567e+03,  1.568e+03,  1.569e+03,  1.571e+03,
        1.572e+03,  1.573e+03,  1.574e+03,  1.575e+03,  1.576e+03,
        1.577e+03,  1.578e+03,  1.579e+03,  1.581e+03,  1.582e+03,
        1.583e+03,  1.584e+03,  1.585e+03,  1.586e+03,  1.587e+03,
        1.588e+03,  1.589e+03,  1.591e+03,  1.592e+03,  1.593e+03,
        1.594e+03,  1.595e+03,  1.596e+03,  1.597e+03,  1.598e+03,
        1.599e+03,  1.601e+03,  1.602e+03,  1.603e+03,  1.604e+03,
        1.605e+03,  1.606e+03,  1.607e+03,  1.608e+03,  1.609e+03,
        1.611e+03,  1.612e+03,  1.613e+03,  1.614e+03,  1.615e+03,
        1.616e+03,  1.617e+03,  1.618e+03,  1.619e+03,  1.621e+03,
        1.622e+03,  1.623e+03,  1.624e+03,  1.625e+03,  1.626e+03,
        1.627e+03,  1.628e+03,  1.629e+03,  1.630e+03,  1.631e+03,
        1.632e+03,  1.633e+03,  1.634e+03,  1.635e+03,  1.636e+03,
        1.637e+03,  1.638e+03,  1.639e+03,  1.640e+03,  1.641e+03,
        1.642e+03,  1.643e+03,  1.644e+03,  1.645e+03,  1.646e+03,
        1.647e+03,  1.648e+03,  1.649e+03,  1.651e+03,  1.652e+03,
        1.653e+03,  1.654e+03,  1.655e+03,  1.656e+03,  1.657e+03,
        1.658e+03,  1.659e+03,  1.660e+03,  1.662e+03,  1.663e+03,
        1.664e+03,  1.665e+03,  1.666e+03,  1.667e+03,  1.668e+03,
        1.669e+03,  1.670e+03,  1.671e+03,  1.672e+03,  1.673e+03,
        1.674e+03,  1.675e+03,  1.676e+03,  1.677e+03,  1.678e+03,
        1.679e+03,  1.680e+03,  1.681e+03,  1.682e+03,  1.683e+03,
        1.684e+03,  1.686e+03,  1.687e+03,  1.688e+03,  1.689e+03,
        1.691e+03,  1.692e+03,  1.693e+03,  1.694e+03,  1.695e+03,
        1.696e+03,  1.697e+03,  1.698e+03,  1.699e+03,  1.701e+03,
        1.702e+03,  1.703e+03,  1.704e+03,  1.706e+03,  1.707e+03,
        1.708e+03,  1.709e+03,  1.711e+03,  1.712e+03,  1.713e+03,
        1.714e+03,  1.715e+03,  1.716e+03,  1.717e+03,  1.718e+03,
        1.719e+03,  1.721e+03,  1.722e+03,  1.723e+03,  1.725e+03,
        1.726e+03,  1.727e+03,  1.728e+03,  1.729e+03,  1.731e+03,
        1.732e+03,  1.733e+03,  1.734e+03,  1.735e+03,  1.736e+03,
        1.737e+03,  1.738e+03,  1.739e+03,  1.741e+03,  1.742e+03,
        1.743e+03,  1.744e+03,  1.745e+03,  1.746e+03,  1.747e+03,
        1.748e+03,  1.749e+03,  1.751e+03,  1.752e+03,  1.753e+03,
        1.754e+03,  1.756e+03,  1.757e+03,  1.758e+03,  1.759e+03,
        1.761e+03,  1.762e+03,  1.763e+03,  1.764e+03,  1.767e+03,
        1.768e+03,  1.769e+03,  1.771e+03,  1.772e+03,  1.773e+03,
        1.774e+03,  1.776e+03,  1.777e+03,  1.778e+03,  1.779e+03,
        1.781e+03,  1.782e+03,  1.783e+03,  1.784e+03,  1.786e+03,
        1.787e+03,  1.788e+03,  1.789e+03,  1.791e+03,  1.793e+03,
        1.794e+03,  1.796e+03,  1.797e+03,  1.798e+03,  1.799e+03,
        1.252e+03,  1.253e+03,  1.254e+03,  1.255e+03,  1.256e+03,
        1.257e+03,  1.258e+03,  1.259e+03,  1.260e+03,  1.261e+03,
        1.262e+03,  1.263e+03,  1.264e+03,  1.265e+03,  1.266e+03,
        1.267e+03,  1.268e+03,  1.269e+03,  1.271e+03,  1.272e+03,
        1.273e+03,  1.274e+03,  1.275e+03,  1.276e+03,  1.277e+03,
        1.278e+03,  1.279e+03])

In [55]:
Life_Exp=Life_Exp.fillna(0)

In [56]:
Life_Exp.head()

,Entity,Year,infant_death,Code_x,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),Death by HIV/AIDS,...,$1.90_PER_DAY_BPL,Life expectancy,GDP per capita,$3.20_PER_DAY_BPL,Death_by_pollution,Death_by_malnutrition,Death_by_Alcohol_Abuse,Death_by_Other_RF,Death_by_Alcohol_&_Drugs,Death_by_other_disease
0,Afghanistan,1990.0,71955.0,AFG,0,2159.0,93.0,1370.0,1538.0,34.0,...,0.0,50.331,963.0000,0.0,78474.0,59699.0,37556.0,33607.0,165.0,72573.0
1,Afghanistan,1991.0,75883.0,AFG,0,2218.0,189.0,1391.0,2001.0,41.0,...,0.0,50.999,881.1704,0.0,81238.0,62535.0,38752.0,34614.0,177.0,77836.0
2,Afghanistan,1992.0,85444.0,AFG,0,2475.0,239.0,1514.0,2299.0,48.0,...,0.0,51.641,843.8753,0.0,87988.0,67541.0,42481.0,36618.0,198.0,86051.0
3,Afghanistan,1993.0,97256.0,AFG,0,2812.0,108.0,1687.0,2589.0,56.0,...,0.0,52.256,578.4027,0.0,96417.0,72461.0,48522.0,39755.0,217.0,95637.0
4,Afghanistan,1994.0,104630.0,AFG,0,3027.0,211.0,1809.0,2849.0,63.0,...,0.0,52.842,428.4246,0.0,100767.0,75317.0,52374.0,40907.0,230.0,100081.0

In [57]:
Life_Exp.describe()

,Year,infant_death,Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),Death by HIV/AIDS,Death by Tuberculosis,Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number),Deaths - Self-harm - Sex: Both - Age: All Ages (Number),...,$1.90_PER_DAY_BPL,Life expectancy,GDP per capita,$3.20_PER_DAY_BPL,Death_by_pollution,Death_by_malnutrition,Death_by_Alcohol_Abuse,Death_by_Other_RF,Death_by_Alcohol_&_Drugs,Death_by_other_disease
count,67814.000000,6.781400e+04,67814.000000,67814.000000,67814.000000,67814.000000,6.781400e+04,6.781400e+04,67814.000000,67814.000000,...,67814.000000,67814.000000,67814.000000,67814.000000,6.781400e+04,6.781400e+04,6.781400e+04,6.781400e+04,67814.000000,6.781400e+04
mean,1650.362374,5.105163e+04,2272.741661,5616.825331,2152.639942,2677.132362,8.209961e+03,9.828996e+03,2931.360235,5080.147285,...,2.059935,17.326992,1965.992812,3.494817,9.389606e+04,1.010988e+05,8.029649e+04,7.598134e+04,1594.675554,1.304540e+05
std,1290.461579,4.856237e+05,21538.948711,58268.309503,20671.894486,23873.597461,8.472314e+04,9.360135e+04,29034.545662,45904.122298,...,10.036345,28.598042,6272.200251,14.632757,8.766103e+05,9.055326e+05,7.176296e+05,6.716234e+05,14620.492953,1.141907e+06
min,-10000.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
25%,1829.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
50%,1910.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
75%,1977.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,42.785250,1225.060800,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
max,2021.000000,1.098801e+07,432524.000000,961129.000000,460665.000000,463129.000000,1.844490e+06,1.808478e+06,757152.000000,841164.000000,...,95.372820,86.751000,156299.000000,99.918440,1.559767e+07,1.975621e+07,1.327602e+07,1.321446e+07,296098.000000,2.173734e+07

In [58]:
Life_Exp.isnull().sum()

Entity                                                                                   0
Year                                                                                     0
infant_death                                                                             0
Code_x                                                                                   0
Number of executions (Amnesty International)                                             0
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                 0
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                    0
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                   0
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                     0
Death by HIV/AIDS                                                                        0
Death by Tuberculosis                                                                    0
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                   0
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                  0
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                     0
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                 0
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                0
Terrorism (deaths)                                                                       0
Death by Cardiovascular disease                                                          0
Death by Kidney disease                                                                  0
Death by Respiratory disease                                                             0
Death by Cirrhosis                                                                       0
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)    0
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                        0
Code_y                                                                                   0
Daily Calorie Intake                                                                     0
Population                                                                               0
Health expenditure per capita                                                            0
World Happiness Index                                                                    0
$1.90_PER_DAY_BPL                                                                        0
Life expectancy                                                                          0
GDP per capita                                                                           0
$3.20_PER_DAY_BPL                                                                        0
Death_by_pollution                                                                       0
Death_by_malnutrition                                                                    0
Death_by_Alcohol_Abuse                                                                   0
Death_by_Other_RF                                                                        0
Death_by_Alcohol_&_Drugs                                                                 0
Death_by_other_disease                                                                   0
dtype: int64

In [59]:
Life_Exp.rename(columns = {'Entity':'Country','Code_x':'Country_Code','Number of executions (Amnesty International)':'Death_by_executions','Deaths - Meningitis - Sex: Both - Age: All Ages (Number)':'Death_by_Meningitis',
'Deaths - Malaria - Sex: Both - Age: All Ages (Number)':'Death_by_Malaria','Deaths - Drowning - Sex: Both - Age: All Ages (Number)':'Death_by_Drowning','Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)':'Death_by_violence',
'Deaths - Self-harm - Sex: Both - Age: All Ages (Number)':'Death_by_Suicide',"Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)":"Death_by_Alzheimer's",
"Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)":"Death_by_Parkinson's"}, inplace = True)

In [60]:
Life_Exp.columns

Index(['Country', 'Year', 'infant_death', 'Country_Code',
       'Death_by_executions', 'Death_by_Meningitis', 'Death_by_Malaria',
       'Death_by_Drowning', 'Death_by_violence', 'Death by HIV/AIDS',
       'Death by Tuberculosis',
       'Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)',
       'Death_by_Suicide',
       'Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)',
       'Deaths - Poisonings - Sex: Both - Age: All Ages (Number)',
       'Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)',
       'Terrorism (deaths)', 'Death by Cardiovascular disease',
       'Death by Kidney disease', 'Death by Respiratory disease',
       'Death by Cirrhosis', 'Death_by_Alzheimer's', 'Death_by_Parkinson's',
       'Code_y', 'Daily Calorie Intake', 'Population',
       'Health expenditure per capita', 'World Happiness Index',
       '$1.90_PER_DAY_BPL', 'Life expectancy', 'GDP per capita',
       '$3.20_PER_DAY_BPL', 'Death_by_pollution', 'Death_by_malnutrition',
       'Death_by_Alcohol_Abuse', 'Death_by_Other_RF',
       'Death_by_Alcohol_&_Drugs', 'Death_by_other_disease'],
      dtype='object')

In [61]:
Life_Exp=Life_Exp[['Country',
       'Year', 
       'Country_Code',
       'GDP per capita',
       'Population',
       'World Happiness Index',
       '$3.20_PER_DAY_BPL',
       '$1.90_PER_DAY_BPL',
       'Health expenditure per capita',
       'infant_death',
       'Death_by_executions', 
	   'Death_by_Meningitis', 
	   'Death_by_Malaria',
       'Death_by_Drowning', 
	   'Death_by_violence',
	   'Death by HIV/AIDS',
       'Death_by_Alcohol_&_Drugs',
       'Death by Tuberculosis',
       'Death_by_Suicide',
       'Terrorism (deaths)',
	   'Death by Cardiovascular disease',
       'Death by Kidney disease',
	   'Death by Respiratory disease',
       'Death by Cirrhosis', 
	   "Death_by_Alzheimer's",
	   "Death_by_Parkinson's",
	   'Daily Calorie Intake',
	   'Death_by_pollution',
	   'Death_by_malnutrition',
       'Death_by_Alcohol_Abuse',
	   'Death_by_Other_RF',
       'Death_by_other_disease',
	   'Life expectancy']]

In [62]:
Life_Exp.nunique()

Country                              467
Year                                 797
Country_Code                         218
GDP per capita                     11344
Population                         51143
World Happiness Index                154
$3.20_PER_DAY_BPL                   6405
$1.90_PER_DAY_BPL                   6084
Health expenditure per capita       4619
infant_death                        6071
Death_by_executions                   82
Death_by_Meningitis                 3652
Death_by_Malaria                    2820
Death_by_Drowning                   3618
Death_by_violence                   3933
Death by HIV/AIDS                   4156
Death_by_Alcohol_&_Drugs            3321
Death by Tuberculosis               4618
Death_by_Suicide                    4634
Terrorism (deaths)                   554
Death by Cardiovascular disease     7247
Death by Kidney disease             5133
Death by Respiratory disease        5793
Death by Cirrhosis                  5344
Death_by_Alzheimer's                4957
Death_by_Parkinson's                3627
Daily Calorie Intake                2736
Death_by_pollution                  7004
Death_by_malnutrition               7409
Death_by_Alcohol_Abuse              7097
Death_by_Other_RF                   7177
Death_by_other_disease              7457
Life expectancy                    15301
dtype: int64

In [63]:
Life_Expectancy_duplicate=Life_Exp[Life_Exp.duplicated()]
Life_Expectancy_duplicate

Empty DataFrame
Columns: [Country, Year, Country_Code, GDP per capita, Population, World Happiness Index, $3.20_PER_DAY_BPL, $1.90_PER_DAY_BPL, Health expenditure per capita, infant_death, Death_by_executions, Death_by_Meningitis, Death_by_Malaria, Death_by_Drowning, Death_by_violence, Death by HIV/AIDS, Death_by_Alcohol_&_Drugs, Death by Tuberculosis, Death_by_Suicide, Terrorism (deaths), Death by Cardiovascular disease, Death by Kidney disease, Death by Respiratory disease, Death by Cirrhosis, Death_by_Alzheimer's, Death_by_Parkinson's, Daily Calorie Intake, Death_by_pollution, Death_by_malnutrition, Death_by_Alcohol_Abuse, Death_by_Other_RF, Death_by_other_disease, Life expectancy]
Index: []

[0 rows x 33 columns]

In [64]:
Life_Exp.shape

(67814, 33)

In [65]:
from geopy.geocoders        import Nominatim
from pycountry_convert      import country_alpha2_to_continent_code,country_name_to_country_alpha2

In [66]:
## Return latitude
def geolocate_lat(country):
    geolocator = Nominatim(user_agent='catuserbot')

    try:
        # Geolocate the center of the country
        loc = geolocator.geocode(country)
        # And return latitude
        return loc.latitude
   
    except:
        # Return missing value
        return np.nan
    
## Return longitude
def geolocate_long(country):
    geolocator = Nominatim(user_agent='catuserbot')

    try:
        # Geolocate the center of the country
        loc = geolocator.geocode(country)
        # And return longitude
        return loc.longitude
   
    except:
        # Return missing value
        return np.nan

In [67]:
#function to convert to alpah2 country codes 


def get_code(col):
    try:
        cn_a2_code = country_name_to_country_alpha2(col)
    except:
        cn_a2_code = 'Unknown'
    try:
        cn_continent = country_alpha2_to_continent_code(cn_a2_code)
    except:
        cn_continent = 'Unknown'
    return (cn_a2_code)

#function to convert to alpah2 country continent

def get_continent(col):
    try:
        cn_a2_code = country_name_to_country_alpha2(col)
    except:
        cn_a2_code = 'Unknown'
    try:
        cn_continent = country_alpha2_to_continent_code(cn_a2_code)
    except:
        cn_continent = 'Unknown'
    return (cn_continent)

In [68]:
Life_Exp['continent'],Life_Exp['code']=Life_Exp['Country'].apply(lambda x: get_continent(x)),Life_Exp['Country'].apply(lambda x: get_code(x))

In [69]:
Life_Exp.continent.unique()

array(['AS', 'Unknown', 'EU', 'AF', 'OC', 'NA', 'SA', 'AN'], dtype=object)

In [70]:
Life_Exp.head()

,Country,Year,Country_Code,GDP per capita,Population,World Happiness Index,$3.20_PER_DAY_BPL,$1.90_PER_DAY_BPL,Health expenditure per capita,infant_death,...,Death_by_Parkinson's,Daily Calorie Intake,Death_by_pollution,Death_by_malnutrition,Death_by_Alcohol_Abuse,Death_by_Other_RF,Death_by_other_disease,Life expectancy,continent,code
0,Afghanistan,1990.0,AFG,963.0000,12412311.0,3.983,0.0,0.0,0.0,71955.0,...,371.0,2314.0,78474.0,59699.0,37556.0,33607.0,72573.0,50.331,AS,AF
1,Afghanistan,1991.0,AFG,881.1704,13299016.0,3.983,0.0,0.0,0.0,75883.0,...,374.0,2044.0,81238.0,62535.0,38752.0,34614.0,77836.0,50.999,AS,AF
2,Afghanistan,1992.0,AFG,843.8753,14485543.0,3.983,0.0,0.0,0.0,85444.0,...,378.0,1891.0,87988.0,67541.0,42481.0,36618.0,86051.0,51.641,AS,AF
3,Afghanistan,1993.0,AFG,578.4027,15816601.0,3.983,0.0,0.0,0.0,97256.0,...,384.0,1910.0,96417.0,72461.0,48522.0,39755.0,95637.0,52.256,AS,AF
4,Afghanistan,1994.0,AFG,428.4246,17075728.0,3.983,0.0,0.0,0.0,104630.0,...,391.0,1820.0,100767.0,75317.0,52374.0,40907.0,100081.0,52.842,AS,AF

In [71]:
Life_Exp.shape

(67814, 35)

In [72]:
Life_Expectancy_duplicate=Life_Exp[Life_Exp.duplicated()]
Life_Expectancy_duplicate

Empty DataFrame
Columns: [Country, Year, Country_Code, GDP per capita, Population, World Happiness Index, $3.20_PER_DAY_BPL, $1.90_PER_DAY_BPL, Health expenditure per capita, infant_death, Death_by_executions, Death_by_Meningitis, Death_by_Malaria, Death_by_Drowning, Death_by_violence, Death by HIV/AIDS, Death_by_Alcohol_&_Drugs, Death by Tuberculosis, Death_by_Suicide, Terrorism (deaths), Death by Cardiovascular disease, Death by Kidney disease, Death by Respiratory disease, Death by Cirrhosis, Death_by_Alzheimer's, Death_by_Parkinson's, Daily Calorie Intake, Death_by_pollution, Death_by_malnutrition, Death_by_Alcohol_Abuse, Death_by_Other_RF, Death_by_other_disease, Life expectancy, continent, code]
Index: []

[0 rows x 35 columns]

In [73]:
Life_Exp.continent.unique()

array(['AS', 'Unknown', 'EU', 'AF', 'OC', 'NA', 'SA', 'AN'], dtype=object)

In [74]:
Life_Exp.Year.unique()

array([ 1.990e+03,  1.991e+03,  1.992e+03,  1.993e+03,  1.994e+03,
        1.995e+03,  1.996e+03,  1.997e+03,  1.998e+03,  1.999e+03,
        2.000e+03,  2.001e+03,  2.002e+03,  2.003e+03,  2.004e+03,
        2.005e+03,  2.006e+03,  2.007e+03,  2.008e+03,  2.009e+03,
        2.010e+03,  2.011e+03,  2.012e+03,  2.013e+03,  2.014e+03,
        2.015e+03,  2.016e+03,  2.017e+03,  2.018e+03,  2.019e+03,
        1.950e+03,  1.951e+03,  1.952e+03,  1.953e+03,  1.954e+03,
        1.955e+03,  1.956e+03,  1.957e+03,  1.958e+03,  1.959e+03,
        1.960e+03,  1.961e+03,  1.962e+03,  1.963e+03,  1.964e+03,
        1.965e+03,  1.966e+03,  1.967e+03,  1.968e+03,  1.969e+03,
        1.970e+03,  1.971e+03,  1.972e+03,  1.973e+03,  1.974e+03,
        1.975e+03,  1.976e+03,  1.977e+03,  1.978e+03,  1.979e+03,
        1.980e+03,  1.981e+03,  1.982e+03,  1.983e+03,  1.984e+03,
        1.985e+03,  1.986e+03,  1.987e+03,  1.988e+03,  1.989e+03,
        2.020e+03, -1.000e+04, -9.000e+03, -8.000e+03, -7.000e+03,
       -6.000e+03, -5.000e+03, -4.000e+03, -3.000e+03, -2.000e+03,
       -1.000e+03,  0.000e+00,  1.000e+02,  2.000e+02,  3.000e+02,
        4.000e+02,  5.000e+02,  6.000e+02,  7.000e+02,  8.000e+02,
        9.000e+02,  1.000e+03,  1.100e+03,  1.200e+03,  1.300e+03,
        1.400e+03,  1.500e+03,  1.600e+03,  1.700e+03,  1.710e+03,
        1.720e+03,  1.730e+03,  1.740e+03,  1.750e+03,  1.760e+03,
        1.770e+03,  1.780e+03,  1.790e+03,  1.800e+03,  1.801e+03,
        1.802e+03,  1.803e+03,  1.804e+03,  1.805e+03,  1.806e+03,
        1.807e+03,  1.808e+03,  1.809e+03,  1.810e+03,  1.811e+03,
        1.812e+03,  1.813e+03,  1.814e+03,  1.815e+03,  1.816e+03,
        1.817e+03,  1.818e+03,  1.819e+03,  1.820e+03,  1.821e+03,
        1.822e+03,  1.823e+03,  1.824e+03,  1.825e+03,  1.826e+03,
        1.827e+03,  1.828e+03,  1.829e+03,  1.830e+03,  1.831e+03,
        1.832e+03,  1.833e+03,  1.834e+03,  1.835e+03,  1.836e+03,
        1.837e+03,  1.838e+03,  1.839e+03,  1.840e+03,  1.841e+03,
        1.842e+03,  1.843e+03,  1.844e+03,  1.845e+03,  1.846e+03,
        1.847e+03,  1.848e+03,  1.849e+03,  1.850e+03,  1.851e+03,
        1.852e+03,  1.853e+03,  1.854e+03,  1.855e+03,  1.856e+03,
        1.857e+03,  1.858e+03,  1.859e+03,  1.860e+03,  1.861e+03,
        1.862e+03,  1.863e+03,  1.864e+03,  1.865e+03,  1.866e+03,
        1.867e+03,  1.868e+03,  1.869e+03,  1.870e+03,  1.871e+03,
        1.872e+03,  1.873e+03,  1.874e+03,  1.875e+03,  1.876e+03,
        1.877e+03,  1.878e+03,  1.879e+03,  1.880e+03,  1.881e+03,
        1.882e+03,  1.883e+03,  1.884e+03,  1.885e+03,  1.886e+03,
        1.887e+03,  1.888e+03,  1.889e+03,  1.890e+03,  1.891e+03,
        1.892e+03,  1.893e+03,  1.894e+03,  1.895e+03,  1.896e+03,
        1.897e+03,  1.898e+03,  1.899e+03,  1.900e+03,  1.901e+03,
        1.902e+03,  1.903e+03,  1.904e+03,  1.905e+03,  1.906e+03,
        1.907e+03,  1.908e+03,  1.909e+03,  1.910e+03,  1.911e+03,
        1.912e+03,  1.913e+03,  1.914e+03,  1.915e+03,  1.916e+03,
        1.917e+03,  1.918e+03,  1.919e+03,  1.920e+03,  1.921e+03,
        1.922e+03,  1.923e+03,  1.924e+03,  1.925e+03,  1.926e+03,
        1.927e+03,  1.928e+03,  1.929e+03,  1.930e+03,  1.931e+03,
        1.932e+03,  1.933e+03,  1.934e+03,  1.935e+03,  1.936e+03,
        1.937e+03,  1.938e+03,  1.939e+03,  1.940e+03,  1.941e+03,
        1.942e+03,  1.943e+03,  1.944e+03,  1.945e+03,  1.946e+03,
        1.947e+03,  1.948e+03,  1.949e+03,  2.021e+03,  1.705e+03,
        1.270e+03,  1.310e+03,  1.380e+03,  1.420e+03,  1.450e+03,
        1.000e+00,  1.550e+03,  1.650e+03,  1.090e+03,  1.120e+03,
        1.410e+03,  1.430e+03,  1.440e+03,  1.460e+03,  1.470e+03,
        1.480e+03,  1.490e+03,  1.510e+03,  1.520e+03,  1.530e+03,
        1.540e+03,  1.560e+03,  1.570e+03,  1.580e+03,  1.590e+03,
        1.610e+03,  1.620e+03,  1.661e+03,  1.685e+03,  1.690e+03,
        1.724e+03,  1.766e+03,  1.775e+03,  1.792e+03,  7.300e+02,
        1.280e+03,  1.755e+03,  1.765e+03,  1.785e+03,  1.795e+03,
        1.281e+03,  1.282e+03,  1.283e+03,  1.284e+03,  1.285e+03,
        1.286e+03,  1.287e+03,  1.288e+03,  1.289e+03,  1.290e+03,
        1.291e+03,  1.292e+03,  1.293e+03,  1.294e+03,  1.295e+03,
        1.296e+03,  1.297e+03,  1.298e+03,  1.299e+03,  1.301e+03,
        1.302e+03,  1.303e+03,  1.304e+03,  1.305e+03,  1.306e+03,
        1.307e+03,  1.308e+03,  1.309e+03,  1.311e+03,  1.312e+03,
        1.313e+03,  1.314e+03,  1.315e+03,  1.316e+03,  1.317e+03,
        1.318e+03,  1.319e+03,  1.320e+03,  1.321e+03,  1.322e+03,
        1.323e+03,  1.324e+03,  1.325e+03,  1.326e+03,  1.327e+03,
        1.328e+03,  1.329e+03,  1.330e+03,  1.331e+03,  1.332e+03,
        1.333e+03,  1.334e+03,  1.335e+03,  1.336e+03,  1.337e+03,
        1.338e+03,  1.339e+03,  1.340e+03,  1.341e+03,  1.342e+03,
        1.343e+03,  1.344e+03,  1.345e+03,  1.346e+03,  1.347e+03,
        1.348e+03,  1.349e+03,  1.350e+03,  1.351e+03,  1.352e+03,
        1.353e+03,  1.354e+03,  1.355e+03,  1.356e+03,  1.357e+03,
        1.358e+03,  1.359e+03,  1.360e+03,  1.361e+03,  1.362e+03,
        1.363e+03,  1.364e+03,  1.365e+03,  1.366e+03,  1.367e+03,
        1.368e+03,  1.369e+03,  1.370e+03,  1.371e+03,  1.372e+03,
        1.373e+03,  1.374e+03,  1.375e+03,  1.376e+03,  1.377e+03,
        1.378e+03,  1.379e+03,  1.381e+03,  1.382e+03,  1.383e+03,
        1.384e+03,  1.385e+03,  1.386e+03,  1.387e+03,  1.388e+03,
        1.389e+03,  1.390e+03,  1.391e+03,  1.392e+03,  1.393e+03,
        1.394e+03,  1.395e+03,  1.396e+03,  1.397e+03,  1.398e+03,
        1.399e+03,  1.401e+03,  1.402e+03,  1.403e+03,  1.404e+03,
        1.405e+03,  1.406e+03,  1.407e+03,  1.408e+03,  1.409e+03,
        1.411e+03,  1.412e+03,  1.413e+03,  1.414e+03,  1.415e+03,
        1.416e+03,  1.417e+03,  1.418e+03,  1.419e+03,  1.421e+03,
        1.422e+03,  1.423e+03,  1.424e+03,  1.425e+03,  1.426e+03,
        1.427e+03,  1.428e+03,  1.429e+03,  1.431e+03,  1.432e+03,
        1.433e+03,  1.434e+03,  1.435e+03,  1.436e+03,  1.437e+03,
        1.438e+03,  1.439e+03,  1.441e+03,  1.442e+03,  1.443e+03,
        1.444e+03,  1.445e+03,  1.446e+03,  1.447e+03,  1.448e+03,
        1.449e+03,  1.451e+03,  1.452e+03,  1.453e+03,  1.454e+03,
        1.455e+03,  1.456e+03,  1.457e+03,  1.458e+03,  1.459e+03,
        1.461e+03,  1.462e+03,  1.463e+03,  1.464e+03,  1.465e+03,
        1.466e+03,  1.467e+03,  1.468e+03,  1.469e+03,  1.471e+03,
        1.472e+03,  1.473e+03,  1.474e+03,  1.475e+03,  1.476e+03,
        1.477e+03,  1.478e+03,  1.479e+03,  1.481e+03,  1.482e+03,
        1.483e+03,  1.484e+03,  1.485e+03,  1.486e+03,  1.487e+03,
        1.488e+03,  1.489e+03,  1.491e+03,  1.492e+03,  1.493e+03,
        1.494e+03,  1.495e+03,  1.496e+03,  1.497e+03,  1.498e+03,
        1.499e+03,  1.501e+03,  1.502e+03,  1.503e+03,  1.504e+03,
        1.505e+03,  1.506e+03,  1.507e+03,  1.508e+03,  1.509e+03,
        1.511e+03,  1.512e+03,  1.513e+03,  1.514e+03,  1.515e+03,
        1.516e+03,  1.517e+03,  1.518e+03,  1.519e+03,  1.521e+03,
        1.522e+03,  1.523e+03,  1.524e+03,  1.525e+03,  1.526e+03,
        1.527e+03,  1.528e+03,  1.529e+03,  1.531e+03,  1.532e+03,
        1.533e+03,  1.534e+03,  1.535e+03,  1.536e+03,  1.537e+03,
        1.538e+03,  1.539e+03,  1.541e+03,  1.542e+03,  1.543e+03,
        1.544e+03,  1.545e+03,  1.546e+03,  1.547e+03,  1.548e+03,
        1.549e+03,  1.551e+03,  1.552e+03,  1.553e+03,  1.554e+03,
        1.555e+03,  1.556e+03,  1.557e+03,  1.558e+03,  1.559e+03,
        1.561e+03,  1.562e+03,  1.563e+03,  1.564e+03,  1.565e+03,
        1.566e+03,  1.567e+03,  1.568e+03,  1.569e+03,  1.571e+03,
        1.572e+03,  1.573e+03,  1.574e+03,  1.575e+03,  1.576e+03,
        1.577e+03,  1.578e+03,  1.579e+03,  1.581e+03,  1.582e+03,
        1.583e+03,  1.584e+03,  1.585e+03,  1.586e+03,  1.587e+03,
        1.588e+03,  1.589e+03,  1.591e+03,  1.592e+03,  1.593e+03,
        1.594e+03,  1.595e+03,  1.596e+03,  1.597e+03,  1.598e+03,
        1.599e+03,  1.601e+03,  1.602e+03,  1.603e+03,  1.604e+03,
        1.605e+03,  1.606e+03,  1.607e+03,  1.608e+03,  1.609e+03,
        1.611e+03,  1.612e+03,  1.613e+03,  1.614e+03,  1.615e+03,
        1.616e+03,  1.617e+03,  1.618e+03,  1.619e+03,  1.621e+03,
        1.622e+03,  1.623e+03,  1.624e+03,  1.625e+03,  1.626e+03,
        1.627e+03,  1.628e+03,  1.629e+03,  1.630e+03,  1.631e+03,
        1.632e+03,  1.633e+03,  1.634e+03,  1.635e+03,  1.636e+03,
        1.637e+03,  1.638e+03,  1.639e+03,  1.640e+03,  1.641e+03,
        1.642e+03,  1.643e+03,  1.644e+03,  1.645e+03,  1.646e+03,
        1.647e+03,  1.648e+03,  1.649e+03,  1.651e+03,  1.652e+03,
        1.653e+03,  1.654e+03,  1.655e+03,  1.656e+03,  1.657e+03,
        1.658e+03,  1.659e+03,  1.660e+03,  1.662e+03,  1.663e+03,
        1.664e+03,  1.665e+03,  1.666e+03,  1.667e+03,  1.668e+03,
        1.669e+03,  1.670e+03,  1.671e+03,  1.672e+03,  1.673e+03,
        1.674e+03,  1.675e+03,  1.676e+03,  1.677e+03,  1.678e+03,
        1.679e+03,  1.680e+03,  1.681e+03,  1.682e+03,  1.683e+03,
        1.684e+03,  1.686e+03,  1.687e+03,  1.688e+03,  1.689e+03,
        1.691e+03,  1.692e+03,  1.693e+03,  1.694e+03,  1.695e+03,
        1.696e+03,  1.697e+03,  1.698e+03,  1.699e+03,  1.701e+03,
        1.702e+03,  1.703e+03,  1.704e+03,  1.706e+03,  1.707e+03,
        1.708e+03,  1.709e+03,  1.711e+03,  1.712e+03,  1.713e+03,
        1.714e+03,  1.715e+03,  1.716e+03,  1.717e+03,  1.718e+03,
        1.719e+03,  1.721e+03,  1.722e+03,  1.723e+03,  1.725e+03,
        1.726e+03,  1.727e+03,  1.728e+03,  1.729e+03,  1.731e+03,
        1.732e+03,  1.733e+03,  1.734e+03,  1.735e+03,  1.736e+03,
        1.737e+03,  1.738e+03,  1.739e+03,  1.741e+03,  1.742e+03,
        1.743e+03,  1.744e+03,  1.745e+03,  1.746e+03,  1.747e+03,
        1.748e+03,  1.749e+03,  1.751e+03,  1.752e+03,  1.753e+03,
        1.754e+03,  1.756e+03,  1.757e+03,  1.758e+03,  1.759e+03,
        1.761e+03,  1.762e+03,  1.763e+03,  1.764e+03,  1.767e+03,
        1.768e+03,  1.769e+03,  1.771e+03,  1.772e+03,  1.773e+03,
        1.774e+03,  1.776e+03,  1.777e+03,  1.778e+03,  1.779e+03,
        1.781e+03,  1.782e+03,  1.783e+03,  1.784e+03,  1.786e+03,
        1.787e+03,  1.788e+03,  1.789e+03,  1.791e+03,  1.793e+03,
        1.794e+03,  1.796e+03,  1.797e+03,  1.798e+03,  1.799e+03,
        1.252e+03,  1.253e+03,  1.254e+03,  1.255e+03,  1.256e+03,
        1.257e+03,  1.258e+03,  1.259e+03,  1.260e+03,  1.261e+03,
        1.262e+03,  1.263e+03,  1.264e+03,  1.265e+03,  1.266e+03,
        1.267e+03,  1.268e+03,  1.269e+03,  1.271e+03,  1.272e+03,
        1.273e+03,  1.274e+03,  1.275e+03,  1.276e+03,  1.277e+03,
        1.278e+03,  1.279e+03])

In [75]:
Life_Exp['continent'] = Life_Exp['continent'].replace({'AS':'Asia','Unknown':'Unknown','EU':'Europe','AF':'Africa','OC':'Oceania','NA':'North America','SA':'South America','AN':'Antarctica'})

In [76]:
Life_Exp.to_csv('Life_Prediction.csv', index=False)